import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {smartContext} from '../../android/web/smart_policy.js';
import {chainWindowAllowed} from '../../android/web/duel-presentation.js';
import {downloadBlob} from '../../android/web/asset-download.js';
import {preloadStartupAssets} from '../../android/web/startup-assets.js';
import {OcgHintTiming as T,OcgLocation as L} from '../../android/web/vendor/package/dist/index.js';
const content=JSON.parse(fs.readFileSync(new URL('../../android/web/content.json',import.meta.url))),cards=new Map(content.cards.map(c=>[c.id,c]));
const byName=n=>content.cards.find(c=>c.name===n),c=(n,controller,location,sequence=0)=>({code:byName(n).id,controller,location,sequence,position:1,attack:byName(n).atk,defense:byName(n).defense});
let own=[c('Magical Scientist',0,L.MZONE)],enemy=[c('Blue-Eyes White Dragon',1,L.MZONE)],back=[],extra=[c('Thousand-Eyes Restrict',0,L.EXTRA),c('Flame Swordsman',0,L.EXTRA,1)];
const e={cards,data:Object.fromEntries(content.cards.map(c=>[c.id,{...c.data,attack:c.atk,defense:c.defense}])),name:id=>cards.get(id)?.name,turn:3,player:0,phase:4,lp:[8000,8000],query:(p,l)=>l===L.MZONE?(p?enemy:own):l===L.EXTRA?(p?[]:extra):l===L.SZONE?(p?[]:back):[],activeChain:[]};
let policy=()=>smartContext(e,0,L,{to_bp:true});
assert.ok(policy().activation(own[0])>0,'Scientist removes stronger opposing monster');
assert.ok(policy().targetScore('Magical Scientist',extra[0],{})>policy().targetScore('Magical Scientist',extra[1],{}),'Choose removal fusion over stats');
enemy=[c('Petit Dragon',1,L.MZONE)];assert.equal(policy().activation(own[0]),-1,'Keep LP against trivial monster');
enemy=[];assert.equal(policy().activation(own[0]),-1,'No target: no spending');
enemy=[c('Blue-Eyes White Dragon',1,L.MZONE)];extra=[extra[1]];assert.equal(policy().activation(own[0]),-1,'No useful removal fusion: conserve LP');
extra.unshift(c('Thousand-Eyes Restrict',0,L.EXTRA));e.lp[0]=2000;assert.equal(policy().activation(own[0]),-1,'Low LP guard');e.lp[0]=8000;
back=Array.from({length:5},(_,i)=>c('Axe of Despair',0,L.SZONE,i));assert.equal(policy().activation(own[0]),-1,'No equip zone');back=[];
own.push(c('Thousand-Eyes Restrict',0,L.MZONE,1));assert.equal(policy().activation(own[0]),-1,'Do not repeat when own removal fusion exists');own.pop();
enemy[0].is_immune=true;assert.equal(policy().activation(own[0]),-1,'Immune threat');delete enemy[0].is_immune;
e.aiModifiers={activeRelics:[['cursed_iron_silence'],[]]};assert.equal(policy().activation(own[0]),-1,'Disabled monster effects');e.aiModifiers={};
console.log('PASS Scientist policy: removal choice, LP and board safety');
const ctx={turnPlayer:1,phase:512,card:id=>cards.get(id)},m=n=>({player:0,selects:[{code:byName(n).id}],hint_timing:T.END_PHASE});
for(const n of ['Mystical Space Typhoon','Dust Tornado','Call of the Haunted'])assert.equal(chainWindowAllowed(m(n),'sometimes',[],ctx),true,n);
assert.equal(chainWindowAllowed(m('Mirror Force'),'sometimes',[],ctx),false);assert.equal(chainWindowAllowed(m('Mystical Space Typhoon'),'sometimes',[],{...ctx,turnPlayer:0}),false);assert.equal(chainWindowAllowed(m('Dust Tornado'),'never',[],ctx),false);assert.equal(chainWindowAllowed({...m('Dust Tornado'),forced:true},'never',[],ctx),true);assert.equal(chainWindowAllowed({player:0,hint_timing:T.ATTACK},'sometimes'),true);
console.log('PASS Chain sometimes: opponent End Phase, card types, forced and never modes');
let attempts=0;assert.equal((await downloadBlob('sound',{request:async()=>{if(++attempts<3)throw Error('offline');return new Response('audio')},delay:async()=>{}})).size,5);assert.equal(attempts,3);
await assert.rejects(downloadBlob('stalled',{request:()=>new Promise(()=>{}),timeout:5,attempts:1}),/timed out/);
let requested=[];const request=async p=>{requested.push(p);return p==='startup-assets.json'?Response.json({audio:['sound.wav','assets/music/track.mp3'],images:['portrait.jpg']}):new Response('data')};
await preloadStartupAssets(()=>{},{fetchAsset:request,images:false,music:false,makeURL:()=> 'blob:test'});assert.deepEqual(requested,['startup-assets.json','sound.wav']);
let failed;await preloadStartupAssets(()=>{},{fetchAsset:async p=>p==='startup-assets.json'?Response.json({audio:['sound.wav'],images:['broken.jpg']}):new Response('',{status:503}),makeURL:()=> 'blob:test',downloadOptions:{delay:async()=>{}},onFailures:f=>failed=f});assert.deepEqual(failed,['broken.jpg']);
await assert.rejects(preloadStartupAssets(()=>{},{fetchAsset:async p=>p==='startup-assets.json'?Response.json({audio:['missing.wav'],images:[]}):new Response('',{status:503}),downloadOptions:{delay:async()=>{}}}),/sound files/);
console.log('PASS startup: audio remains required, optional artwork nonfatal, retries and stalled fetch timeout');
// Service-worker install with a permanent failure, followed by a successful retry.
const cacheMaps=new Map(),events={},posts=[],counts=new Map();let fail=true;
const caches={keys:async()=>[...cacheMaps.keys()],open:async name=>{if(!cacheMaps.has(name))cacheMaps.set(name,new Map());const map=cacheMaps.get(name);return {match:async k=>map.get(String(k))?.clone(),put:async(k,r)=>map.set(String(k),r.clone())}},delete:async n=>cacheMaps.delete(n)};
const source=fs.readFileSync(new URL('../../tools/pwa/pwa-sw.js',import.meta.url),'utf8').replace('__VERSION__','"test"').replace('__FILES__','["index.html","good.jpg","bad.jpg"]');
const context={URL,Request,Response,Headers,AbortController,caches,setTimeout:(f,t)=>setTimeout(f,t===90000?1000:0),clearTimeout,fetch:async req=>{const url=req.url;counts.set(url,(counts.get(url)||0)+1);if(fail&&url.endsWith('bad.jpg'))throw Error('network');return new Response('ok')},self:{location:{href:'https://game.test/sw.js'},clients:{matchAll:async()=>[{postMessage:m=>posts.push(m)}],claim:async()=>{}},addEventListener:(n,f)=>events[n]=f}};vm.runInNewContext(source,context);
const install=()=>{let result;events.install({waitUntil:p=>result=p});return result};await assert.rejects(install(),/network/);assert.ok(cacheMaps.has('ygo-rogue-test'));assert.equal(counts.get('https://game.test/bad.jpg'),3);fail=false;await install();assert.equal(counts.get('https://game.test/good.jpg'),1);assert.equal(counts.get('https://game.test/bad.jpg'),4);assert.equal(posts.at(-1).type,'CACHE_READY');console.log('PASS offline interrupted installation reuses completed files');
