import fs from 'node:fs';
import assert from 'node:assert/strict';
import {MobileDuel,M,L,I} from './web/duel.js';
import {smartContext} from './web/smart_policy.js';
const meta=JSON.parse(fs.readFileSync(new URL('./web/content.json',import.meta.url)));
const data=JSON.parse(fs.readFileSync(new URL('./web/engine-data.json',import.meta.url)));
const id=n=>{const c=meta.cards.find(c=>c.name===n);assert(c,n);return c.id};
let checks=0;
for(const p of [0,1]){
 const e=new MobileDuel(meta.cards);Object.assign(e,{data,lp:[8000,8000],player:p,phase:4,activeChain:[],battleProtected:[false,false]});
 let zones={};e.query=(side,loc)=>zones[side+':'+loc]||[];
 const card=(n,side,loc,seq=0,extra={})=>({code:id(n),controller:side,location:loc,sequence:seq,position:loc===L.MZONE?1:8,attack:data[id(n)].attack,defense:data[id(n)].defense,...extra});
 const put=(side,loc,...cards)=>zones[side+':'+loc]=cards;
 const reset=()=>{zones={};e.lp=[8000,8000];e.player=p;e.phase=4;e.attackCard=null;e.attackTarget=null;e.activeChain=[];e.lastSummoned=[]};
 const setup=(n)=>{reset();const c=card(n,p,L.HAND);put(p,L.HAND,c);return c};
 const decision=(c,prompt)=>smartContext(e,p,L,prompt).activation(c,true);
 const yes=(v,msg)=>{assert(v>=0,msg);checks++};const no=(v,msg)=>{assert(v<0,msg);checks++};
 let c=setup('Raigeki');put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));no(decision(c),'Save wipe against a lone ordinary monster');
 put(p,L.MZONE,card('Blue-Eyes White Dragon',p,L.MZONE));no(decision(c),'Battle clears weak target safely');
 c=setup('Fissure');put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));put(p,L.MZONE,card('Blue-Eyes White Dragon',p,L.MZONE));no(decision(c),'Save narrow removal for a target battle cannot clear');
 e.lp[1-p]=2500;yes(decision(c),'Spend removal to open reliable lethal');
 c=setup('Raigeki');put(1-p,L.MZONE,card('Blue-Eyes White Dragon',1-p,L.MZONE),card('Summoned Skull',1-p,L.MZONE,1));yes(decision(c),'Wipe two substantial threats');
 c=setup('Dark Hole');put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE),card('Battle Ox',1-p,L.MZONE,1));put(p,L.MZONE,card('Blue-Eyes White Dragon',p,L.MZONE),card('Blue-Eyes White Dragon',p,L.MZONE,1));no(decision(c),'Do not wipe our superior board');
 c=setup('Fissure');put(1-p,L.MZONE,card('Fire Princess',1-p,L.MZONE));yes(decision(c),'Weak repeated burn engine deserves removal');
 put(1-p,L.MZONE,card('Fire Princess',1-p,L.MZONE,0,{position:8}));no(decision(c),'Fissure cannot hit a set monster');
 c=setup('Raigeki Break');put(p,L.HAND,c,card('Blue-Eyes White Dragon',p,L.HAND,1));put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));no(decision(c),'Do not discard valuable resources for an ordinary target');
 put(1-p,L.MZONE,card('Fire Princess',1-p,L.MZONE));yes(decision(c),'Discard cost justified against active engine');
 put(p,L.HAND,c,card('Exodia the Forbidden One',p,L.HAND,1));no(decision(c),'Never plan to discard an Exodia piece');
 c=setup('Compulsory Evacuation Device');put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));no(decision(c),'Do not bounce irrelevant normal summon');
 e.player=1-p;e.lp[p]=1000;e.attackCard=e.query(1-p,L.MZONE)[0];yes(decision(c),'Bounce attacker to prevent lethal');
 c=setup('Ring of Destruction');put(1-p,L.MZONE,card('Blue-Eyes White Dragon',1-p,L.MZONE));e.lp[p]=3000;no(decision(c),'Conservation never bypasses Ring suicide check');
 e.lp[p]=4000;e.lp[1-p]=3000;yes(decision(c),'Ring secures safe lethal');
 c=setup('Raigeki Break');let cheap=card('Fissure',p,L.HAND,1);put(p,L.HAND,c,cheap,card('Battle Ox',p,L.HAND,2));put(1-p,L.MZONE,card('Blue-Eyes White Dragon',1-p,L.MZONE));
 no(decision(c,{activates:[c,cheap]}),'Prefer offered narrow answer over discard');yes(decision(cheap,{activates:[c,cheap]}),'Narrow answer remains usable');
 put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE,0,{attack:500}),card('Blue-Eyes White Dragon',1-p,L.MZONE,1));no(decision(cheap),'Fissure must evaluate its weakest forced target');
 c=setup('Raigeki Break');put(p,L.HAND,c,card('Battle Ox',p,L.HAND,1));put(1-p,L.MZONE,card('Fire Princess',1-p,L.MZONE),card('Blue-Eyes White Dragon',1-p,L.MZONE,1));let policy=smartContext(e,p,L);
 assert(policy.targetScore('Raigeki Break',e.query(1-p,L.MZONE)[0],{})>policy.targetScore('Raigeki Break',e.query(1-p,L.MZONE)[1],{}),'Target engine over printed ATK');checks++;
 c=setup('Mystical Space Typhoon');put(1-p,L.SZONE,card('Swords of Revealing Light',1-p,L.SZONE,0,{position:1}));yes(decision(c),'Remove battle lock');
 put(1-p,L.SZONE,card('Swords of Revealing Light',1-p,L.SZONE));yes(decision(c),'MST can clear an unknown set card without knowing its identity');
 c=setup('Heavy Storm');put(1-p,L.SZONE,card('Messenger of Peace',1-p,L.SZONE,0,{position:1}),card('Wave-Motion Cannon',1-p,L.SZONE,1,{position:1}));yes(decision(c),'Clear dangerous back row');
 put(p,L.SZONE,card('Wave-Motion Cannon',p,L.SZONE,0,{position:1}),card('Wave-Motion Cannon',p,L.SZONE,1,{position:1}));no(decision(c),'Preserve valuable own back row');
 c=setup('Sakuretsu Armor');e.player=1-p;put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));e.attackCard=e.query(1-p,L.MZONE)[0];put(p,L.MZONE,card('Blue-Eyes White Dragon',p,L.MZONE,0,{position:4,defense:1000}));e.attackTarget=e.query(p,L.MZONE)[0];yes(decision(c),'Protect valuable defending monster');
 c=setup('Trap Hole');e.player=1-p;put(1-p,L.MZONE,card('Blue-Eyes White Dragon',1-p,L.MZONE),card('Battle Ox',1-p,L.MZONE,1));e.lastSummoned=[e.query(1-p,L.MZONE)[1]];no(decision(c),'Old boss does not justify trap on unimportant new summon');
 c=setup('Raigeki Break');e.player=1-p;e.lp[p]=1000;put(p,L.HAND,c,card('Battle Ox',p,L.HAND,1));put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE),card('Blue-Eyes White Dragon',1-p,L.MZONE,1));e.attackCard=e.query(1-p,L.MZONE)[0];yes(decision(c),'Answer lethal from smaller attacker');
 policy=smartContext(e,p,L);assert(policy.targetScore('Raigeki Break',e.query(1-p,L.MZONE)[0],{})>policy.targetScore('Raigeki Break',e.query(1-p,L.MZONE)[1],{}),'Remove actual lethal attacker');checks++;
 c=setup('Nobleman of Crossout');put(1-p,L.MZONE,card('Mystical Elf',1-p,L.MZONE,0,{position:8}));yes(decision(c),'Specialized anti-set answer can be spent on a set monster');
 c=setup('Raigeki');put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));put(p,L.MZONE,card('Blue-Eyes White Dragon',p,L.MZONE));e.lp[1-p]=2000;put(p,L.SZONE,card('Gravity Bind',p,L.SZONE,0,{position:1}));no(decision(c),'Own battle lock prevents false lethal claim');
 c=setup('Raigeki');put(1-p,L.MZONE,card('Battle Ox',1-p,L.MZONE));
 const prompt={type:M.SELECT_IDLECMD,player:p,activates:[c],summons:[],special_summons:[],pos_changes:[],monster_sets:[],spell_sets:[],to_bp:true,to_ep:true};
 const result=e.auto(prompt);assert(result.action!==I.SELECT_ACTIVATE,'Final auto fallback must honor conservation');checks++;
}
console.log(`PASS ${checks} resource-conservation decisions across both seats, including final auto fallback`);
