const {chromium}=require('C:/Users/Win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:896,height:414},hasTouch:true,isMobile:true});const errors=[];page.on('pageerror',e=>errors.push(String(e)));try{
await page.goto('http://127.0.0.1:4181');await page.waitForFunction(()=>window.shadowTest,{timeout:90000});await page.evaluate(async()=>{await shadowTest.command('new',0);shadowTest.go('draft')});
await page.locator('.draft-scroll').evaluate(e=>e.scrollTop=260);const el=page.locator('[data-pick="18"]');await el.scrollIntoViewIfNeeded();const top=await page.locator('.draft-scroll').evaluate(e=>e.scrollTop);const before=await page.evaluate(()=>shadowTest.state().run.selected.includes(18));await el.tap();await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>shadowTest.state().run.selected.includes(18)),!before);assert.equal(await page.locator('.draft-scroll').evaluate(e=>e.scrollTop),top);console.log('PASS single tap toggles once and preserves scroll');
await el.tap();await page.waitForTimeout(80);await el.tap();await page.waitForSelector('dialog[open]');assert.equal(await page.evaluate(()=>shadowTest.state().run.selected.includes(18)),!before);await page.locator('[data-do="close"]').tap();assert.equal(await page.locator('.draft-scroll').evaluate(e=>e.scrollTop),top);console.log('PASS double tap previews without changing deck or scroll');
const cdp=await page.context().newCDPSession(page);let box=await el.boundingBox();const x=box.x+box.width/2,y=Math.min(box.y+30,300);const touch=(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y}]});await touch('touchStart',x,y);await page.waitForTimeout(800);await touch('touchEnd');await page.waitForTimeout(400);assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.evaluate(()=>shadowTest.state().run.selected.includes(18)),!before);console.log('PASS hold does not preview or toggle');
const selected=await page.evaluate(()=>JSON.stringify(shadowTest.state().run.selected));await touch('touchStart',x,y);for(let i=1;i<=8;i++){await touch('touchMove',x,y-i*15);await page.waitForTimeout(40)}await touch('touchEnd');await page.waitForTimeout(450);assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(shadowTest.state().run.selected)),selected);assert.notEqual(await page.locator('.draft-scroll').evaluate(e=>e.scrollTop),top);console.log('PASS native drag scroll without selecting or previewing');
assert.deepEqual(errors,[]);console.log('PASS no runtime errors');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
