const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const root=path.resolve('android/web');const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.end();return}fs.readFile(file,(err,body)=>{if(err){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(body)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,channel:'chrome',env:{...process.env,TEMP:path.resolve('temp'),TMP:path.resolve('temp')}});try{
 const page=await browser.newPage({viewport:{width:924,height:416},hasTouch:true,isMobile:true});await page.route('**/mobile.js',route=>route.fulfill({contentType:'text/javascript',body:''}));await page.goto(origin+'/index.html');
 const result=await page.evaluate(async()=>{const {preloadCards,cardImages}=await import('./card-assets.js');const meta=await(await fetch('content.json')).json();let ticks=0,last=0;const start=performance.now();const r=await preloadCards([...meta.cards,...meta.tokenCards],({loaded,total})=>{if(loaded<last)throw Error('Counter went backwards');last=loaded;ticks++;document.querySelector('#loading-count').textContent=`${loaded} / ${total} cards loaded`;const bar=document.querySelector('progress');bar.max=total;bar.value=loaded});const image=new Image();image.src=cardImages.get(meta.cards[0].id);await image.decode();return {...r,ticks,seconds:(performance.now()-start)/1000,ready:image.naturalWidth>0}});
 assert.equal(result.loaded,result.total);assert(result.total>1800);assert(result.ticks>1800);assert(result.ready);console.log('PASS phone-ratio real image preload:',JSON.stringify(result));
 const failure=await page.evaluate(async()=>{const {preloadCards,cardImages}=await import('./card-assets.js');let fail=false,revoked=0;try{await preloadCards([{id:-1},{id:-2}],()=>{},{fetchImage:async url=>({ok:!url.includes('-1'),blob:async()=>new Blob(['bad'])}),validateImage:async()=>{throw Error('corrupt')},makeURL:()=> 'test-url',revokeURL:()=>revoked++})}catch{fail=true}const retry=await preloadCards([{id:-1},{id:-1}],()=>{},{fetchImage:async()=>({ok:true,blob:async()=>new Blob()}),validateImage:async()=>{},makeURL:()=> 'retry-url'});return {fail,revoked,retry,badCached:cardImages.has(-2)}});
 assert(failure.fail);assert.equal(failure.revoked,1);assert.equal(failure.retry.loaded,1);assert(!failure.badCached);console.log('PASS missing/corrupt images fail cleanly, invalid URLs released, deduplicated retry succeeds');
 }finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
