import {GENRES,TYPES,CARD_GENRES} from './card-genres.js';
export {GENRES,TYPES};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tests=GENRES.map(g=>[g,g.pattern?new RegExp(g.pattern,'i'):null]);
export function genres(c){if(!c||((c.data?.type&17)===17))return [];if(CARD_GENRES[c.id])return GENRES.filter(g=>CARD_GENRES[c.id].includes(g.id));return tests.filter(([g,re])=>g.flag?!!(c.data?.type&g.flag):re.test(c.desc||'')).map(([g])=>g)}
export function typeIcon(c){const file=TYPES[String(c.race||'').replace(/[^a-z]/gi,'')];return c.data?.type&1&&file?`<img class="genre-icon" src="assets/icons/yugipedia/${file}" alt="" title="${escape(c.race)}">`:''}
export function genreIcons(c){return `<div class="effect-icons" aria-label="Effect categories">${genres(c).map(g=>`<img class="genre-icon" src="assets/icons/yugipedia/${g.icon}" alt="${escape(g.name)}" title="${escape(g.name)}">`).join('')}</div>`}
export const searches={};
export function matchesSearch(c,key){const s=searches[key]||{};if(!c)return false;const text=(c.name+' '+c.desc).toLowerCase();if(s.q&&!s.q.toLowerCase().split(/\s+/).every(w=>text.includes(w)))return false;if(s.race&&c.race!==s.race)return false;if(s.attribute&&c.attribute!==s.attribute)return false;if(s.level&&(!(c.data.type&1)||c.level!==+s.level))return false;const tags=genres(c).map(g=>g.id);return !s.effects?.length||(s.all?s.effects.every(id=>tags.includes(id)):s.effects.some(id=>tags.includes(id)))}
export function searchButton(key){const s=searches[key],n=s?(s.effects?.length||0)+!!s.q+!!s.race+!!s.attribute+!!s.level:0;return `<button type="button" data-effect-search="${key}" title="Search card text and effects" aria-label="Search card text and effects${n?', '+n+' filters active':''}"><img class="genre-icon" src="assets/icons/yugipedia/genres-search-deck.png" alt="">${n?`<small>${n}</small>`:''}</button>`}
export function openSearch(key,cards,onApply){
 const s=structuredClone(searches[key]||{effects:[]}),d=document.createElement('dialog');d.className='effect-search';
 const options=(values,value)=>'<option value="">—</option>'+values.map(v=>`<option ${v===value?'selected':''}>${escape(v)}</option>`).join('');
 d.innerHTML=`<form method="dialog"><header><input name="q" aria-label="Search names and effect text" placeholder="Search names / effect text" value="${escape(s.q)}"><button value="cancel" aria-label="Close">×</button></header><div class="search-fields"><select name="race" title="Monster Type" aria-label="Monster Type">${options([...new Set(cards.filter(c=>c.data.type&1).map(c=>c.race))].sort(),s.race)}</select><select name="attribute" title="Attribute" aria-label="Attribute">${options(['EARTH','WATER','FIRE','WIND','LIGHT','DARK','DIVINE'],s.attribute)}</select><select name="level" title="Level" aria-label="Level">${options(Array.from({length:12},(_,i)=>String(i+1)),s.level)}</select><select name="match" aria-label="Match effect categories"><option value="any">Any selected</option><option value="all" ${s.all?'selected':''}>All selected</option></select></div><div class="effect-icon-grid">${GENRES.map(g=>`<button type="button" data-genre="${g.id}" title="${escape(g.name)}" aria-label="${escape(g.name)}" aria-pressed="${s.effects.includes(g.id)}"><img src="assets/icons/yugipedia/${g.icon}" alt=""></button>`).join('')}</div><footer><output></output><button type="button" data-reset>Reset</button><button value="apply">Apply</button></footer></form>`;
 const form=d.querySelector('form');const read=()=>({...Object.fromEntries(new FormData(form)),all:form.elements.match.value==='all',effects:[...s.effects]});
 const count=()=>{const old=searches[key];searches[key]=read();d.querySelector('output').textContent=cards.filter(c=>matchesSearch(c,key)).length+' cards';searches[key]=old};
 d.addEventListener('click',e=>{const b=e.target.closest('[data-genre]');if(b){const id=b.dataset.genre;s.effects=s.effects.includes(id)?s.effects.filter(x=>x!==id):[...s.effects,id];b.setAttribute('aria-pressed',String(s.effects.includes(id)));count()}if(e.target.closest('[data-reset]')){form.reset();for(const k of ['q','race','attribute','level'])form.elements[k].value='';form.elements.match.value='any';s.effects=[];d.querySelectorAll('[data-genre]').forEach(b=>b.setAttribute('aria-pressed','false'));count()}});
 form.addEventListener('input',count);d.addEventListener('close',()=>{if(d.returnValue==='apply'){searches[key]=read();onApply()}d.remove()});document.body.append(d);d.showModal();count();
}
