import {validEmote,showDuelEmote,clearDuelEmotes} from './duel-emotes.js';
import {lastPlayed} from './experience-ui.js';
import {collectorIntroductionMarkup,collectorLanding} from './collector-introduction.js';
import {collectorRosterMarkup} from './collector-roster.js';
import {validateDeck,deckCards,rankFor,LIMITS,moveSideCard} from './collector-rules.js';
import {decode} from './tag-session.js';
import {TagDuel} from './tag-duel.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,extra='')=>`<button data-collector="${action}" ${extra}>${text}</button>`;
const collectorLimitIcon=limit=>limit<3?`<i class="collector-limit-icon limit-${limit}" title="${limit===1?'Limited':'Semi-limited'}: maximum ${limit} across all decks" aria-label="${limit===1?'Limited':'Semi-limited'}, maximum ${limit} copies">${limit}</i>`:'';
export class CollectorUI {
 constructor(options){Object.assign(this,options);this.mode='roster';this.isCollector=true;this.alive=true;this.queue=Promise.resolve();this.session={connected:false,code:'',request:(a,v)=>this.enqueue(()=>this.request(a,v))};this.click=e=>{const el=e.target.closest('[data-collector],[data-collector-slot]');if(!el)return;e.stopImmediatePropagation();if(this.held){this.held=false;return;}this.enqueue(()=>this.action(el.dataset.collector||(el.dataset.do==='collector-select'?'select':'import'),el));};document.addEventListener('click',this.click,true);this.down=e=>{const card=e.target.closest('[data-collector=toggle],[data-collector=prize]');if(!card||e.button!==0)return;this.origin=[e.clientX,e.clientY];this.held=false;this.hold=setTimeout(()=>{this.held=true;this.inspect(+card.dataset.id)},450);};this.cancelHold=()=>clearTimeout(this.hold);this.move=e=>{if(this.origin&&Math.hypot(e.clientX-this.origin[0],e.clientY-this.origin[1])>10)this.cancelHold();};document.addEventListener('pointerdown',this.down);document.addEventListener('pointermove',this.move);document.addEventListener('pointerup',this.cancelHold);document.addEventListener('pointercancel',this.cancelHold);}
 enqueue(fn){const next=this.queue.then(()=>this.alive?fn():undefined);this.queue=next.catch(e=>{if(!this.alive)return;this.status=e.message;this.dialog('Ultimate Collector',`<p>${esc(e.message)}</p>`)});return this.queue;}
 init(){const pending=this.queue.then(()=>this.initialize());this.queue=pending.catch(()=>{});return pending;}
 async initialize(){const config=await fetch('./multiplayer-config.json').then(r=>r.json());this.endpoint=(config.signalingUrl||'').replace(/\/$/,'');if(!this.endpoint)throw Error('Online service is not configured.');if(!this.alive)return;this.data=await this.backend('collector-list');if(!this.alive)return;for(const d of this.data.duelists.filter(d=>d.status==='alive')){this.duelist=d;const result=await this.api('register',{duelist:d});if(!this.alive)return;await this.sync(result);if(!this.alive)return;if(result.room&&result.room.phase!=='complete'){this.restoring=true;try{await this.accept(result);}finally{this.restoring=false;this.schedule();}return;}if(result.record.status!=='alive'){await this.accept(result);return;}}this.duelist=null;this.render();}
 async api(op,body={}){const d=this.duelist;const response=await fetch(`${this.endpoint}/collector/${op}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id,token:d.token,...body},(_,v)=>typeof v==='bigint'?{__bigint:String(v)}:v),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Collector service unavailable.');return result;}
 async sync(result){this.data=await this.backend('collector-sync',{id:this.duelist.id,record:result.record});this.duelist=this.data.duelists.find(d=>d.id===this.duelist.id);}
 schedule(){clearTimeout(this.timer);if(!this.alive||!this.room||this.room.phase==='complete')return;this.timer=setTimeout(()=>this.enqueue(async()=>{try{await this.accept(await this.api('poll'));this.session.connected=true;}catch(e){this.session.connected=false;this.status='Connection interrupted. Reconnecting automatically…';if(this.mode!=='duel')this.render();}finally{this.schedule();}}),1500);}
 async accept(result){if(!this.alive)return;await this.sync(result);if(!this.alive)return;this.room=result.record.room?result.room:null;this.seat=result.seat;this.serverOffset=result.now-Date.now();this.updateReconnectTimer();this.session.code=this.room?.code||'';this.session.connected=true;
 if(this.duelist.status!=='alive'){this.game?.destroy();this.game=null;this.mode='shadow';this.view={phase:'gameover'};this.onView(this.view);this.onResult?.(false);this.render();return;}
 const r=this.room;if(r?.phase!=='duel')clearDuelEmotes();if(r?.phase==='duel'){this.seenEmotes??={};for(const [seat,event] of Object.entries(r.emotes||{})){const key=r.code+':'+seat;if(this.seenEmotes[key]===event.id)continue;this.seenEmotes[key]=event.id;if(!this.restoring&&event.game===r.game&&result.now-event.at<5000)showDuelEmote(event.emoji,+seat===this.seat);}}if(!r){this.mode='home';this.render();return;}
 if(r.phase==='duel'){if(this.restoring)this.coinRoom=r.code;if(!this.restoring&&r.game===1&&!r.events.length&&this.coinRoom!==r.code){this.coinRoom=r.code;const coin=document.createElement('div');coin.className='collector-coin-toss';coin.innerHTML=`<div class="collector-coin">${r.first===this.seat?'YOU':'OPPONENT'}</div><p>${r.first===this.seat?'You go first':'Opponent goes first'}</p>`;document.body.append(coin);await new Promise(resolve=>setTimeout(resolve,1560));coin.remove();}if(!this.alive)return;this.mode='duel';this.view={phase:'duel',characters:r.players.map(p=>p.character),modifiers:[],run:{character:this.duelist.character,opponent:r.players[1-this.seat].character,pool:this.duelist.pool,selected:[],artifacts:[],curses:[],challenge_level:0,lp:8000,gold:0,round:1,stats:{},duel:{id:r.code+'-'+r.game}}};this.onView(this.view);await this.updateDuel(r);return;}
 this.game?.destroy();this.game=null;this.view={phase:r.phase};this.onView(this.view);this.mode=r.phase==='siding'?'siding':r.phase==='waiting'?'waiting':r.claimed?'home':this.prizeRoom===r.code?'prizes':'victory';if(this.mode==='victory')this.onResult?.(true);if(this.mode==='siding'&&this.sidingGame!==r.game){this.sidingGame=r.game;this.draft=structuredClone(r.decks[this.seat]);this.section='main';this.filter='All';this.search='';}this.render();}
 updateReconnectTimer(){
 clearInterval(this.countdown);if(!this.alive)return;const draw=()=>{
  const r=this.room,last=r?.seen?.[1-this.seat],now=Date.now()+(this.serverOffset||0);
  const visible=this.alive&&this.session.connected&&r?.players.length===2&&r.phase!=='complete'&&Number.isFinite(last)&&now-last>20000;
  let el=document.getElementById('collector-reconnect-timer');
  if(!visible){el?.remove();return;}
  if(!el){el=document.createElement('div');el.id='collector-reconnect-timer';el.setAttribute('role','status');document.body.append(el);}
  const seconds=Math.max(0,Math.ceil(((r.disconnectLeft?.[1-this.seat]??300000)-Math.max(0,now-last-(r.charged?.[1-this.seat]||0)))/1000));
  el.textContent=`Opponent disconnected · Reconnect time remaining ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
 };const update=()=>{draw();this.drawTurnTimer();};update();this.countdown=setInterval(update,1000);
 }
 drawTurnTimer(){
 const r=this.room;let el=document.getElementById('collector-turn-timer');if(!this.alive||r?.phase!=='duel'){el?.remove();return;}
 if(!el){el=document.createElement('div');el.id='collector-turn-timer';el.setAttribute('role','timer');document.body.append(el);}
 const now=Date.now()+(this.serverOffset||0),paused=!this.session.connected||r.seen.some(t=>now-t>=15000),actor=r.actor;
 const format=seat=>{const ms=(r.turnLeft?.[seat]??180000)-(actor===seat&&!paused?Math.max(0,now-r.clockAt):0);const sec=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;};
 el.textContent=`You ${format(this.seat)} · Opponent ${format(1-this.seat)}${paused?' · Paused':''}`;
 }
 async updateDuel(r){if(!this.alive)return;const key=r.code+':'+r.game,engineSeat=this.seat^r.first;let fresh=false;
 if(this.gameKey!==key||!this.game){this.game?.destroy();this.game=new TagDuel([...this.content.cards,...this.content.tokenCards]);const created=this.game;await created.init();if(!this.alive){created.destroy();return;}this.gameKey=key;this.applied=0;this.shown=-1;const order=[r.first,1-r.first];this.game.startTag({teams:order.map(i=>[{main:r.decks[i].main,extra:r.decks[i].extra}]),lp:8000,enemyLP:8000,seed:r.seed,mode:'pvp',rules:2,names:order.map(i=>[this.content.characters[r.players[i].character].name])});fresh=true;}
 while(this.applied<r.events.length){const event=r.events[this.applied];this.game.respondFor(event.seat^r.first,this.applied,decode(structuredClone(event.response)));this.applied++;}
 if(fresh||this.shown!==this.applied){const visuals=this.game.visuals.splice(0),cues=(this.restoring||fresh&&this.applied)?[]:this.game.cuesFor(engineSeat,visuals);const snap=this.game.snapshotFor(engineSeat);await this.onDuel(snap,cues);if(!this.alive)return;this.shown=this.applied;}
 const clockKey=key+':'+this.applied;if(this.clockSent!==clockKey){try{await this.api('clock',{number:this.applied,turn:this.game.turn||1,actor:this.game.respondingSeat===null?null:this.game.respondingSeat^r.first});this.clockSent=clockKey;}catch(error){this.status=error.message;}}
 if(!this.alive)return;
 if(this.game.finished&&!this.resultSent?.includes(key)){const winner=this.game.finished.player;await this.api('result',{number:this.applied,winner:winner===0||winner===1?winner^r.first:2});this.resultSent=[...(this.resultSent||[]),key];}
 }
 async request(action,value){if(action==='emote'){if(this.room?.phase!=='duel'||!validEmote(value))return;if(Date.now()-(this.lastEmote||0)<1500)return;this.lastEmote=Date.now();await this.accept(await this.api('emote',{emoji:value,game:this.room.game}));}else if(action==='duel-response'){if(!this.game||this.game.respondingSeat!==(this.seat^this.room.first))throw Error('Wait for your opponent.');const number=this.applied;if(value.number!==number)throw Error('That choice is stale. Refresh the duel.');try{this.game.respondFor(this.seat^this.room.first,number,value.response);this.applied++;await this.accept(await this.api('response',{seat:this.seat,number,response:value.response,nextActor:this.game.respondingSeat===null?null:this.game.respondingSeat^this.room.first,turn:this.game.turn||1}));}catch(error){this.game?.destroy();this.game=null;await this.accept(await this.api('poll'));throw error;}}else if(action==='surrender'){await this.accept(await this.api('surrender',{game:this.room.game}));}this.schedule();}
 render(){if(!this.alive||this.mode==='duel')return;const oldScroll=this.root.querySelector('.collector-content')?.scrollTop||0,oldCards=this.root.querySelector('.cardgrid')?.scrollTop||0,keepScroll=this.lastRenderedMode===this.mode;this.lastRenderedMode=this.mode;const d=this.duelist,r=this.room;let body='';
 if(this.mode==='roster'){body=(collectorLanding(this.data.duelists)==='introduction'?collectorIntroductionMarkup():'')+collectorRosterMarkup(this.data.duelists,this.content.characters);}
 else if(this.mode==='import'){body='<h2>Choose a saved run</h2><p>This permanently moves the selected save out of single player.</p><div class="save-slot-grid">'+this.getSlots().map(s=>{const r=s.run,c=r?this.content.characters[r.character]:null,inDuel=r?.stage==='duel',eligible=r&&c&&!c.copycat&&!inDuel;return `<button class="save-slot" data-collector="select-import" data-source="${s.slot}" ${eligible?'':'disabled'}><span class="slot-number">Slot ${s.slot}${c?' · '+esc(c.name):''}</span><span class="slot-portrait">${c?`<img src="assets/${esc(c.sprite)}" alt="${esc(c.name)}">`:''}</span><span class="slot-detail">${r?`Loop ${(r.loop||0)+1} · Duel ${Math.min(9,(r.round||0)+1)}/9<br>${Number(r.lp||0).toLocaleString()} LP<br><small>Last played: ${esc(lastPlayed(r.last_played_at))}</small>`:'Empty'}</span><b class="slot-action">${inDuel?'finish your duel to import this collector':eligible?'Select this run':r?'Copycat cannot be imported':'Empty'}</b></button>`}).join('')+'</div>';}
 else if(this.mode==='import-name'){const s=this.getSlots().find(s=>s.slot===this.importSource),c=this.content.characters[s.run.character];body=`<section class="tag-join-screen"><h2>Name your duelist</h2><p>Slot ${s.slot} · ${esc(c.name)}</p><label for="collector-name">Duelist name</label><input id="collector-name" maxlength="32" autocomplete="off"><p>This permanently moves this save out of single player.</p><div>${button('Back','import-back')}${button('Import','move',`data-source="${s.slot}"`)}</div></section>`;}
 else if(this.mode==='shadow'){body=this.resultMarkup(false);}
 else if(this.mode==='home'){const legal=validateDeck(d.draftDeck||d.deck,d.pool,this.content.cards).length===0;body=`<h2>${esc(d.name)} · ${rankFor(d.wins)}</h2><div class="collector-home">${button('Edit deck','edit')}${button('Duelist history','history',legal?'':'disabled')}${button('Host','host',legal?'':'disabled')}${button('Join','join',legal?'':'disabled')}</div>`+(legal?'':'<p>Build a legal Main Deck to unlock the other options.</p>');}
 else if(this.mode==='editor'||this.mode==='siding'){body=this.editor();}
 else if(this.mode==='join'){body='<section class="tag-join-screen"><h2>Join a room</h2><label for="collector-code">Enter room code</label><input id="collector-code" maxlength="5" autocapitalize="characters" autocorrect="off" spellcheck="false" autocomplete="off" placeholder="ABCDE" aria-label="Room code"><div>'+button('Back','home')+button('Join','join-room')+'</div></section>';}
 else if(this.mode==='waiting'){body=`<section class="tag-room collector-room"><div class="tag-room-heading"><div><small>ROOM CODE</small><strong class="collector-lobby-code">${esc(r.code)}</strong></div><h2>${r.players.length} / 2 players</h2></div><div class="tag-room-players">${[0,1].map(i=>{const p=r.players[i],c=p?this.content.characters[p.character]:null;return `<div class="tag-player-portrait ${p?'':'tag-empty'}">${c?`<img src="assets/${esc(c.sprite)}" alt="${esc(c.name)}">`:''}<strong>${p?esc(p.name):'Waiting for opponent'}</strong></div>`}).join('')}</div><p>${r.players.length===2?'Opponent joined. Preparing the duel…':'Waiting for an opponent…'}</p>${button('Cancel room','leave')}</section>`;}
 else if(this.mode==='history'){body=`<h2>${rankFor(d.wins)} · ${d.wins} match wins</h2>`+d.history.map(h=>`<section class="panel"><h3>${h.won?'Won':'Lost'} against ${esc(h.opponent||'opponent')}</h3><p>${esc(h.reason)}</p><p>${(h.games||[]).map(g=>`Game ${g.game}: ${esc(g.result)} · ${g.turns} turns`).join('<br>')}</p><div class="collector-cards">${(h.cards||[]).map(id=>this.cardTile(id,'inspect')).join('')}</div></section>`).join('');}
 else if(this.mode==='victory'){body=this.resultMarkup(true);}
 else if(this.mode==='prizes'){const limitsByName=new Map();for(const c of this.content.cards)limitsByName.set(c.name,Math.min(limitsByName.get(c.name)??3,LIMITS[c.id]??3));body=`<h2>Match won · ${rankFor(d.wins)}</h2>`;if(r.claimed)body+='<p>Your prize cards are in your collection.</p>'+button('Return to roster','roster');else{body+=`<div class="collector-prizes"><p class="draft-count">${this.prizeSet?.size||0} / 5 prize cards selected</p><p class="draft-inspect-help">Tap to select · Hold a card to inspect · Drag to scroll</p><div class="cardgrid">${r.prizes.map((id,i)=>{const c=this.content.cards.find(c=>c.id===id),selected=this.prizeSet?.has(i);return `<button class="cardbtn ${selected?'selected':''}" data-collector="prize" data-index="${i}" data-id="${id}" aria-pressed="${!!selected}">${collectorLimitIcon(limitsByName.get(c?.name)??3)}<img src="${this.image(id)}" alt="${esc(c?.name)}"><span>${esc(c?.name)}</span></button>`}).join('')}</div><button class="duel-confirm collector-prize-confirm" data-collector="claim" aria-label="Claim five selected cards" title="Claim five selected cards" ${this.prizeSet?.size===5?'':'disabled'}><span class="duel-decision-icon" aria-hidden="true">✓</span></button></div>`;}}
 if(this.mode==='siding'&&r.ready.every(Boolean)&&r.nextFirst==null){body+=`<div class="collector-first-overlay"><section role="dialog" aria-modal="true" aria-label="Choose who starts"><h2>${r.chooser===this.seat?'Choose who starts':'Waiting for opponent'}</h2><p>${r.chooser===this.seat?'Siding is complete. You lost the previous duel, so you choose who starts.':'Siding is complete. Your opponent is choosing who starts.'}</p>${r.chooser===this.seat?button('I go first','first','data-first="'+this.seat+'"')+button('Opponent goes first','first','data-first="'+(1-this.seat)+'"'):''}</section></div>`;}
 this.root.innerHTML=`<div class="collector-page"><header><h1>Ultimate Collector</h1><small>${r&&r.phase!=='complete'?'Room '+esc(r.code):''}</small>${button('Help','help')}${button('Back','back')}</header><div class="collector-content">${this.status?`<p role="status">${esc(this.status)}</p>`:''}${body}</div></div>`;if(keepScroll){this.root.querySelector('.collector-content').scrollTop=oldScroll;const grid=this.root.querySelector('.cardgrid');if(grid)grid.scrollTop=oldCards;}}
 resultMarkup(won){const d=this.duelist,c=this.content.characters[d.character];return `<section class="collector-result ${won?'triumph':'shadow-realm'}">${won?'<div class="collector-result-aura" aria-hidden="true"></div>':`<div class="collector-defeat-particles" aria-hidden="true">${Array.from({length:28},(_,i)=>`<i style="--x:${(i*37+11)%100}%;--y:${(i*53+7)%100}%;--size:${2+i%4}px;--drift:${(i%2?1:-1)*(12+i%23)}px;--duration:${8+i%7}s;--delay:-${i*.73}s"></i>`).join('')}</div>`}<img class="collector-result-portrait" src="assets/${esc(c.sprite)}" alt="${esc(c.name)}"><p class="collector-result-kicker">${won?'The Gods favored you':'THE SHADOWS HAVE CLAIMED YOU'}</p><h2>${won?'VICTORY':"YOUR DUELIST WAS SENT TO THE SHADOW REALM"}</h2><p class="collector-result-name">${esc(d.name)}</p><p>${won?`${rankFor(d.wins)} · Your collection lives on.`:'This duelist and their collection are lost forever.'}</p>${button(won?'Claim your five prize cards':'Return to Ultimate Collector',won?'open-prizes':'roster')}</section>`;}
 cardTile(id,action,index=id,selected=false){const c=this.content.cards.find(c=>c.id===id);return `<div class="collector-card ${selected?'selected':''}">${button(`<img src="${this.image(id)}" alt="${esc(c?.name)}"><span>${esc(c?.name)}</span>`,action,`data-index="${index}" data-id="${id}"`)}${action==='inspect'?'':button('Inspect','inspect',`data-id="${id}"`)}</div>`;}
 editor(){
 const siding=this.mode==='siding',r=this.room,pool=siding?deckCards(r.startDecks[this.seat]):this.duelist.pool;
 const chosen={},reserved={};for(const id of this.draft[this.section])chosen[id]=(chosen[id]||0)+1;for(const zone of ['main','side','extra'])if(zone!==this.section)for(const id of this.draft[zone])reserved[id]=(reserved[id]||0)+1;
 const cards=new Map(this.content.cards.map(c=>[c.id,c])),first=new Map(),last=new Map();pool.forEach((id,i)=>{if(!first.has(id))first.set(id,i);last.set(id,i)});
 const limitsByName=new Map();for(const c of this.content.cards)limitsByName.set(c.name,Math.min(limitsByName.get(c.name)??3,LIMITS[c.id]??3));
 const order=[...(siding?this.draft[this.section]:pool)],mode=this.sort||'Color',name=id=>(cards.get(id)?.name||'').toLowerCase(),category=id=>{const t=cards.get(id)?.data.type||0;return t&1?0:t&2?1:t&4?2:3};
 order.sort((a,b)=>{const ca=cards.get(a)||{},cb=cards.get(b)||{},byName=name(a).localeCompare(name(b));if(mode==='Name')return byName;if(mode==='Color'){const color=c=>{const t=c.data?.type||0;return t&2?4:t&4?5:t&64?3:t&128?2:t&16?0:1};return color(ca)-color(cb)||byName}if(mode==='Attribute')return String(ca.attribute||'').localeCompare(String(cb.attribute||''))||byName;if(mode==='Color'){const color=c=>{const t=c.data?.type||0;return t&2?4:t&4?5:t&64?3:t&128?2:t&16?0:1};return color(ca)-color(cb)||byName}if(mode==='Attribute')return String(ca.attribute||'').localeCompare(String(cb.attribute||''))||byName;if(mode==='Type')return category(a)-category(b)||String(ca.type||ca.race||'').localeCompare(String(cb.type||cb.race||''))||byName;if(['ATK','DEF','LVL'].includes(mode)){const key={ATK:'atk',DEF:'defense',LVL:'level'}[mode];return (cb[key]||0)-(ca[key]||0)||byName}return mode==='Newest'?last.get(b)-last.get(a):first.get(a)-first.get(b)});
 const rows=[];for(const id of order){if(!siding&&reserved[id]){reserved[id]--;continue;}const selected=!!chosen[id];if(selected)chosen[id]--;const c=this.content.cards.find(c=>c.id===id);if(!c)continue;
 if(this.section==='extra'&&!(c.data.type&64)||this.section==='main'&&(c.data.type&64))continue;
 if(!(c.name+' '+c.desc).toLowerCase().includes((this.search||'').toLowerCase()))continue;
 const filter=this.filter||'All';if(filter==='Deck'&&!selected||filter==='Monster'&&!(c.data.type&1)||filter==='Spell'&&!(c.data.type&2)||filter==='Trap'&&!(c.data.type&4))continue;
 const restriction=collectorLimitIcon(limitsByName.get(c.name)??3);
 rows.push(`<button class="cardbtn ${!siding&&selected?'selected':''}" data-collector="toggle" data-id="${id}" data-selected="${selected}" aria-pressed="${!siding&&selected}">${restriction}<img draggable="false" loading="lazy" src="${this.image(id)}" alt="${esc(c.name)}"><span>${esc(c.name)}</span></button>`);
 }
 const errors=validateDeck(this.draft,pool,this.content.cards,siding?r.startDecks[this.seat]:null);
 return `<div class="collector-deck-editor"><div class="draft-summary"><div><p class="draft-count">${this.draft.main.length} / ${siding?r.startDecks[this.seat].main.length:'40–60'} main · ${this.draft.side.length} / 15 side · ${this.draft.extra.length} / 15 Fusion</p><p class="draft-inspect-help">${siding?'Tap a card to move it between Main and Side (Fusion cards use Fusion).':'Tap to select'} · Hold a card to inspect · Drag to scroll</p></div></div><nav class="draft-tabs">${['main','side','extra'].map(s=>button(({main:'Main Deck',side:'Side Deck',extra:'Fusion Deck'})[s],'section',`data-section="${s}" class="${this.section===s?'active':''}"`)).join('')}</nav><div class="draft-tabs">${['All','Monster','Spell','Trap','Deck'].map(f=>button(f,'filter',`data-filter="${f}" class="${(this.filter||'All')===f?'active':''}"`)).join('')}<input id="collector-search" placeholder="Search cards" value="${esc(this.search||'')}">${button('Search','search')}<div class="draft-tabs" aria-label="Sort cards">${['Color','Name','Type','ATK','DEF','LVL','Attribute'].map(sort=>button(sort,'sort',`data-sort="${sort}" class="${(this.sort||'Color')===sort?'active':''}"`)).join('')}</div></div><div class="cardgrid">${rows.join('')||'<p>No available cards match this filter.</p>'}</div><footer class="collector-deck-footer"><p>${errors.map(esc).join('<br>')||(siding?'Deck sizes restored. Ready for the next duel.':'Deck is legal.')}</p>${siding?button('Ready for next duel','ready',errors.length?'disabled':''):'<span>Changes saved automatically</span>'}${siding?button('Reset changes','reset-siding'):button('Deselect all','deselect')}${siding?`<p>${r.ready[1-this.seat]?'Opponent ready':'Waiting for opponent to finish siding'}</p>`:''}</footer></div>`;
 }
 async action(action,el={dataset:{}}){const x=el.dataset;
 if(action==='open-prizes'){this.prizeRoom=this.room.code;this.mode='prizes';this.render();return;}
 if(action==='help'){this.dialog('Ultimate Collector',collectorIntroductionMarkup());return;}
 if(action==='inspect'){this.inspect(+x.id);return;}
 if(action==='exit'||action==='back'){if(this.room&&this.room.phase!=='complete'){this.dialog('Leave Ultimate Collector?',`<p>Your match remains active. Reopen Ultimate Collector within five minutes to reconnect or your duelist will be lost.</p>${button('Leave and reconnect later','exit-now')}`);return;}if(this.mode==='roster'){this.destroy();await this.onExit();return;}this.mode=['editor','history','join'].includes(this.mode)?'home':this.mode==='import-name'?'import':'roster';this.render();return;}
 if(action==='exit-now'){document.querySelector('dialog[open]')?.close();this.destroy();await this.onExit();return;}
 if(action==='roster'){this.room=null;this.mode='roster';this.duelist=null;this.render();return;}
 if(action==='select'){this.duelist=this.data.duelists.find(d=>d.status==='alive'&&d.slot===+x.collectorSlot);await this.accept(await this.api('poll'));this.schedule();return;}
 if(action==='home'){this.mode='home';}
 if(action==='import-back'){this.mode='import';}
 if(action==='select-import'){const s=this.getSlots().find(s=>s.slot===+x.source);if(s?.run?.stage==='duel'){this.dialog('Ultimate Collector','<p>finish your duel to import this collector</p>');return;}if(!s?.run||this.content.characters[s.run.character]?.copycat)return;this.importSource=+x.source;this.mode='import-name';}
 if(action==='import'){this.importSlot=+x.collectorSlot;this.mode='import';}
 if(action==='move'){const name=document.getElementById('collector-name').value;this.data=await this.backend('collector-import',{source:+x.source,slot:this.importSlot,name});this.duelist=this.data.duelists.find(d=>d.status==='alive'&&d.slot===this.importSlot);await this.accept(await this.api('register',{duelist:this.duelist}));return;}
 if(action==='edit'){this.draft=structuredClone(this.duelist.draftDeck||this.duelist.deck);this.section='main';this.mode='editor';}
 if(action==='section'){this.section=x.section;if(this.mode!=='siding')this.mode='editor';}
 if(action==='sort')this.sort=x.sort;
 if(action==='filter')this.filter=x.filter;
 if(action==='reset-siding'&&this.mode==='siding')this.draft=structuredClone(this.room.decks[this.seat]);
 if(action==='deselect'&&this.mode!=='siding')this.draft[this.section]=[];
 if(action==='toggle'){if(this.mode==='siding'){moveSideCard(this.draft,this.section,+x.id,this.content.cards);}else if(x.selected==='true'){const i=this.draft[this.section].indexOf(+x.id);if(i>=0)this.draft[this.section].splice(i,1);}else this.draft[this.section].push(+x.id);}
 if(action==='add'&&this.mode!=='siding'){this.draft[this.section].push(+x.id);}
 if(action==='remove'&&this.mode!=='siding'){this.draft[this.section].splice(+x.index,1);}
 if(action==='search')this.search=document.getElementById('collector-search').value;
 if(this.mode==='editor'&&['toggle','deselect','add','remove'].includes(action)){this.data=await this.backend('collector-draft',{id:this.duelist.id,deck:this.draft});this.duelist=this.data.duelists.find(d=>d.id===this.duelist.id);}
 if(action==='history')this.mode='history';
 if(action==='host'||action==='join-room'){await this.sync(await this.api('deck',{deck:this.duelist.draftDeck||this.duelist.deck}));await this.accept(await this.api(action==='host'?'host':'join',{code:document.getElementById('collector-code')?.value}));this.schedule();return;}
 if(action==='join')this.mode='join';
 if(action==='leave'){await this.accept(await this.api('leave'));return;}
 if(action==='ready'){await this.accept(await this.api('side',{deck:this.draft}));this.schedule();return;}
 if(action==='first'){await this.accept(await this.api('first',{first:+x.first}));this.schedule();return;}
 if(action==='prize'){this.prizeSet??=new Set();const i=+x.index;if(this.prizeSet.has(i))this.prizeSet.delete(i);else if(this.prizeSet.size<5)this.prizeSet.add(i);}
 if(action==='claim'){await this.accept(await this.api('prizes',{indices:[...this.prizeSet]}));this.prizeSet.clear();return;}
 this.render();}
 destroy(){this.alive=false;clearInterval(this.countdown);document.getElementById('collector-reconnect-timer')?.remove();document.getElementById('collector-turn-timer')?.remove();clearTimeout(this.timer);this.game?.destroy();document.removeEventListener('click',this.click,true);clearTimeout(this.hold);document.removeEventListener('pointerdown',this.down);document.removeEventListener('pointermove',this.move);document.removeEventListener('pointerup',this.cancelHold);document.removeEventListener('pointercancel',this.cancelHold);}
}
