import {startRecording,recordResponse,saveRecording} from './replays.js';
import createCore,{OcgDuelMode as D,OcgLocation as L,OcgPosition as P,OcgQueryFlags as Q,OcgMessageType as M,OcgResponseType as R,SelectIdleCMDAction as I,SelectBattleCMDAction as B,cardMatchesOpcode,OcgRace,OcgAttribute,ocgMessageTypeStrings} from './vendor/package/dist/index.js';
import {systemStrings} from './system-strings.js';
export {M,R,I,B,L,P};
export function expandedSeed(seed){let state=BigInt.asUintN(64,BigInt(seed));return Array.from({length:4},()=>{state=BigInt.asUintN(64,state+0x9e3779b97f4a7c15n);let z=state;z=BigInt.asUintN(64,(z^(z>>30n))*0xbf58476d1ce4e5b9n);z=BigInt.asUintN(64,(z^(z>>27n))*0x94d049bb133111ebn);return BigInt.asUintN(64,z^(z>>31n));});}
export function loadDuelResources(){return Promise.all([fetch('engine-data.json').then(r=>{if(!r.ok)throw Error('Could not load duel data');return r.json()}),fetch('scripts.json').then(r=>r.json())]);}
export class DuelEngine{
 constructor(cards){this.cards=new Map(cards.map(c=>[c.id,c]));this.logs=[];this.errors=[];this.turn=0;this.phase=0;this.player=0;this.pending=null;this.finished=null;this.last=null;}
 async init(resources){const [data,scripts]=resources||await loadDuelResources();this.data=data;this.scripts={...scripts};
 // The bundled core predates the Link (31) and Pendulum-scale (32) chain queries. Vintage cards
 // have no Pendulum scale, but newer utility scripts query it on registration.
 if(this.scripts['chain.lua']&&![...this.cards.values()].some(c=>c.data?.type&0x1000000))this.scripts['chain.lua']=this.scripts['chain.lua'].replace('Chain.GetTriggeringScale            = chaininfo_fn(CHAININFO_TRIGGERING_LSCALE)','Chain.GetTriggeringScale            = function() return 0 end');
if(this.scripts['chain.lua']&&![...this.cards.values()].some(c=>c.data?.type&0x4000000))this.scripts['chain.lua']=this.scripts['chain.lua'].replace('Chain.GetTriggeringLink             = chaininfo_fn(CHAININFO_TRIGGERING_LINK)','Chain.GetTriggeringLink             = function() return 0 end');
for(const c of Object.values(data))c.race=BigInt(c.race);this.core=await createCore({sync:true});return this;}
 start(deck,enemy,lp,enemyLP,draw=5,seed=Date.now(),extra=[],enemyExtra=[],passives="",enemyDraw=5,tagTeams=null){startRecording(this,[deck,enemy,lp,enemyLP,draw,seed,extra,enemyExtra,passives,enemyDraw,tagTeams]);this.deckReversed=false;this.revealedTop=[null,null];this.lp=[lp,enemyLP];this.logs=[];this.errors=[];this.finished=null;this.turn=0;this.pending=null;this.h=this.core.createDuel({flags:D.MODE_MR1??D.MODE_GOAT,seed:passives.includes('-- SHADOW_RUN_RNG 2')?expandedSeed(seed):[BigInt(seed),17n,71n,31n],team1:{startingLP:lp,startingDrawCount:draw,drawCountPerTurn:1},team2:{startingLP:enemyLP,startingDrawCount:enemyDraw,drawCountPerTurn:1},cardReader:code=>this.data[code]||null,scriptReader:name=>this.scripts[name.split('/').pop()]||null,errorHandler:(type,text)=>{this.errors.push(text);console.error('OCG',text)}});if(!this.h)throw Error('EDOPro could not create the duel.');for(const name of ['constant.lua','utility.lua'])this.core.loadScript(this.h,name,this.scripts[name]);const teams=tagTeams||[[{main:deck,extra}],[{main:enemy,extra:enemyExtra}]];for(const [team,duelists] of teams.entries())for(const [duelist,cards] of duelists.entries())for(const [location,codes] of [[L.DECK,cards.main],[L.EXTRA,cards.extra||[]]])for(const code of codes)this.core.duelNewCard(this.h,{code,team,duelist,controller:team,location,sequence:0,position:P.FACEDOWN_DEFENSE});this.core.startDuel(this.h);if(passives)this.core.loadScript(this.h,"shadow-passives.lua",passives);return this.advance();}
 name(code){return this.cards.get(code)?.name||'Card '+code;}
 description(v){if(v===undefined||v===null)return '';const n=BigInt(v);if(systemStrings[String(n)]){const raw=systemStrings[String(n)],m=this.pending||{},c=m.card||m;let i=0;const args=[this.name(c.code||this.effect?.code||0),({2:'hand',4:'Monster Zone',8:'Spell & Trap Zone',16:'Graveyard',32:'banished zone'})[c.location]||'field'];return raw.replace(/%(?:\d+\$)?l?s/g,()=>args[i++]||'card');}const modern=this.cards.get(Number(n>>20n));if(modern)return modern.strings?.[Number(n&0xfffffn)]||'';const legacy=this.cards.get(Number(n>>4n));return legacy?.strings?.[Number(n&15n)]||'';}
 advance(){this.pending=null;for(let step=0;step<1000;step++){const status=this.core.duelProcess(this.h);const messages=this.core.duelGetMessage(this.h);for(const m of messages){this.last=m;if(m.type===M.REVERSE_DECK){this.deckReversed=!this.deckReversed;if(!this.deckReversed)this.revealedTop=[null,null];}if(m.type===M.DECK_TOP&&m.count===0)this.revealedTop[m.player]=(m.position&5)?m.code:null;this.onMessage?.(m);if(m.type===M.RETRY)throw Error('The engine rejected that selection. Please choose a different legal response.');if(m.type===M.NEW_TURN){this.turn++;this.player=m.player;this.logs.unshift(`Turn ${this.turn} · ${m.player===0?'Your turn':'Opponent’s turn'}`)}if(m.type===M.NEW_PHASE)this.phase=m.phase;if(m.type===M.DAMAGE||m.type===M.PAY_LPCOST){this.lp[m.player]=Math.max(0,this.lp[m.player]-m.amount);this.logs.unshift(`${m.player===0?'You':'Opponent'} ${m.type===M.DAMAGE?'take':'pay'} ${m.amount} LP.`)}if(m.type===M.RECOVER){this.lp[m.player]+=m.amount;this.logs.unshift(`${m.player===0?'You':'Opponent'} recover ${m.amount} LP.`)}if(m.type===M.LPUPDATE)this.lp[m.player]=m.lp;if([M.SUMMONING,M.SPSUMMONING,M.FLIPSUMMONING].includes(m.type))this.logs.unshift(`${m.controller===0?'You summon':'Opponent summons'} ${this.name(m.code)}.`);if(m.type===M.CHAINING)this.logs.unshift(`${this.name(m.code)} activates.`);if(m.type===M.WIN)this.finished=m;const type=ocgMessageTypeStrings.get(m.type);if(type&&(type.startsWith('select_')||type.startsWith('announce_')||type==='sort_card'||type==='sort_chain'||type==='rock_paper_scissors'))this.pending=m;}this.logs=this.logs.slice(0,70);if(this.finished||status===0)return this.snapshot();if(status===1){if(this.pending?.type===M.SELECT_CHAIN&&!this.pending.forced&&!this.pending.selects.length){this.core.duelSetResponse(this.h,{type:R.SELECT_CHAIN,index:null});this.pending=null;continue}if(!this.pending)throw Error('Duel is waiting without a recognized prompt.');return this.snapshot()}}throw Error('Duel processing exceeded its safe step limit.');}
 respond(response){const prev=this.pending;this.core.duelSetResponse(this.h,response);try{const result=this.advance();recordResponse(this,response);return result}catch(e){this.pending=prev;throw e}}
 query(player,location){return this.core.duelQueryLocation(this.h,{controller:player,location,flags:Q.CODE|Q.POSITION|Q.ATTACK|Q.DEFENSE|Q.LEVEL|Q.IS_PUBLIC|Q.COUNTERS|Q.STATUS|Q.ATTRIBUTE|Q.EQUIP_CARD})?.map((c,sequence)=>c?{...c,controller:player,location,sequence,type:this.data[c.code]?.type||0}:null)||[];}
 snapshot(){return {lp:this.lp,turn:this.turn,phase:this.phase,player:this.player,pending:this.pending,finished:this.finished,players:[0,1].map(p=>({monsters:this.query(p,L.MZONE).slice(0,5),spells:this.query(p,L.SZONE),hand:this.query(p,L.HAND),grave:this.query(p,L.GRAVE),banished:this.query(p,L.REMOVED),deck:this.core.duelQueryCount(this.h,p,L.DECK),extra:this.core.duelQueryCount(this.h,p,L.EXTRA),deckTop:this.deckReversed?this.query(p,L.DECK).filter(Boolean).at(-1)?.code:this.revealedTop[p]}))};}
 choices(m=this.pending){if(!m)return [];let out=[];const add=(label,response,code)=>out.push({label,response,code});const addlist=(arr,label,type,action)=>arr.forEach((c,index)=>add(`${label} · ${this.name(c.code)}${label==='Activate'&&this.description(c.description)?' — '+this.description(c.description):''}`,{type,action,index},c.code));switch(m.type){case M.SELECT_IDLECMD:addlist(m.summons,'Summon',R.SELECT_IDLECMD,I.SELECT_SUMMON);addlist(m.special_summons,'Special summon',R.SELECT_IDLECMD,I.SELECT_SPECIAL_SUMMON);addlist(m.monster_sets,'Set monster',R.SELECT_IDLECMD,I.SELECT_MONSTER_SET);addlist(m.spell_sets,'Set spell / trap',R.SELECT_IDLECMD,I.SELECT_SPELL_SET);addlist(m.activates,'Activate',R.SELECT_IDLECMD,I.SELECT_ACTIVATE);addlist(m.pos_changes,'Change position',R.SELECT_IDLECMD,I.SELECT_POS_CHANGE);if(m.to_bp)add('Enter battle phase →',{type:R.SELECT_IDLECMD,action:I.TO_BP,index:null});if(m.to_ep)add('End turn →',{type:R.SELECT_IDLECMD,action:I.TO_EP,index:null});break;
 case M.SELECT_BATTLECMD:addlist(m.attacks,'Attack',R.SELECT_BATTLECMD,B.SELECT_BATTLE);addlist(m.chains,'Activate',R.SELECT_BATTLECMD,B.SELECT_CHAIN);if(m.to_m2)add('Main phase 2 →',{type:R.SELECT_BATTLECMD,action:B.TO_M2,index:null});if(m.to_ep)add('End turn →',{type:R.SELECT_BATTLECMD,action:B.TO_EP,index:null});break;
 case M.SELECT_CHAIN:m.selects.forEach((c,index)=>add((this.chainDepth?'Chain':'Activate')+' · '+this.name(c.code)+(this.description(c.description)?' — '+this.description(c.description):''),{type:R.SELECT_CHAIN,index},c.code));if(!m.forced)add(this.chainDepth?'Do not chain':'Do not activate',{type:R.SELECT_CHAIN,index:null});break;
 case M.SELECT_EFFECTYN:case M.SELECT_YESNO:for(const yes of [true,false])add(yes?'Yes · activate / confirm':'No · decline',{type:m.type===M.SELECT_EFFECTYN?R.SELECT_EFFECTYN:R.SELECT_YESNO,yes},m.code);break;
 case M.SELECT_OPTION:m.options.forEach((v,index)=>add(`${index+1}: ${this.description(v)||'Resolve effect'}`,{type:R.SELECT_OPTION,index}));break;
 case M.SELECT_POSITION:for(const [position,label]of [[1,'Face-up attack'],[4,'Face-up defense'],[8,'Face-down defense'],[2,'Face-down attack']])if(m.positions&position)add(label,{type:R.SELECT_POSITION,position});break;
 case M.SELECT_PLACE:case M.SELECT_DISFIELD:{let places=[];for(let side=0;side<2;side++)for(const [location,offset,count]of [[L.MZONE,0,5],[L.SZONE,8,8]])for(let seq=0;seq<count;seq++)if(!(m.field_mask&(1<<(side*16+offset+seq))))places.push({player:side===0?m.player:1-m.player,location,sequence:seq});for(const p of places)add(`${p.player===m.player?'Your':'Opponent’s'} ${p.location===L.MZONE?'monster':'spell / trap'} zone ${p.sequence+1}`,{type:m.type===M.SELECT_PLACE?R.SELECT_PLACE:R.SELECT_DISFIELD,places:[p]});break;}
 case M.SELECT_UNSELECT_CARD:m.select_cards.forEach((c,index)=>add('Select · '+this.name(c.code),{type:R.SELECT_UNSELECT_CARD,index},c.code));m.unselect_cards.forEach((c,i)=>add('Unselect · '+this.name(c.code),{type:R.SELECT_UNSELECT_CARD,index:m.select_cards.length+i},c.code));if(m.can_finish||m.can_cancel)add(m.can_finish?'Finish selection':'Cancel',{type:R.SELECT_UNSELECT_CARD,index:null});break;
 case M.SORT_CARD:case M.SORT_CHAIN:add('Keep this order',{type:R.SORT_CARD,order:null});break;
 case M.ANNOUNCE_NUMBER:m.options.forEach((v,index)=>add(String(v),{type:R.ANNOUNCE_NUMBER,value:index}));break;
 case M.ANNOUNCE_CARD:for(const c of this.cards.values())if(cardMatchesOpcode(this.data[c.id],m.opcodes))add(c.name,{type:R.ANNOUNCE_CARD,card:c.id},c.id);break;
 case M.ROCK_PAPER_SCISSORS:['Rock','Paper','Scissors'].forEach((v,i)=>add(v,{type:R.ROCK_PAPER_SCISSORS,value:i+1}));break;
 }return out;}
 auto(m=this.pending){const choices=this.choices(m),p=m.player;const atk=c=>this.data[c.code]?.attack||0;const ranked=arr=>arr.map((c,i)=>({c,i})).sort((a,b)=>atk(b.c)-atk(a.c));switch(m.type){case M.SELECT_IDLECMD:{const summoned=ranked(m.summons)[0];if(summoned)return {type:R.SELECT_IDLECMD,action:I.SELECT_SUMMON,index:summoned.i};if(m.spell_sets.length)return {type:R.SELECT_IDLECMD,action:I.SELECT_SPELL_SET,index:0};if(m.to_bp)return {type:R.SELECT_IDLECMD,action:I.TO_BP,index:null};return {type:R.SELECT_IDLECMD,action:I.TO_EP,index:null}}
 case M.SELECT_BATTLECMD:{const theirs=this.query(1-p,L.MZONE).filter(Boolean);const attack=m.attacks.findIndex(c=>{const own=this.core.duelQuery(this.h,{controller:p,location:L.MZONE,sequence:c.sequence,flags:Q.ATTACK});return theirs.length===0||theirs.some(t=>!(t.position&5)||(own?.attack||0)>=(t.position&1?t.attack:t.defense))});if(attack>=0)return{type:R.SELECT_BATTLECMD,action:B.SELECT_BATTLE,index:attack};return {type:R.SELECT_BATTLECMD,action:B.TO_EP,index:null}}
 case M.SELECT_CHAIN:return {type:R.SELECT_CHAIN,index:m.forced?0:null};
 case M.SELECT_CARD:case M.SELECT_TRIBUTE:{const selected=m.selects.map((c,i)=>({c,i})).sort((a,b)=>atk(a.c)-atk(b.c));let indices=[],amount=0;for(const x of selected){if(amount>=m.min)break;indices.push(x.i);amount+=m.type===M.SELECT_TRIBUTE?(x.c.release_param||1):1}return {type:m.type===M.SELECT_CARD?R.SELECT_CARD:R.SELECT_TRIBUTE,indicies:indices}}
 case M.SELECT_SUM:return {type:R.SELECT_SUM,indicies:this.sumSelection(m)};
 case M.SELECT_EFFECTYN:case M.SELECT_YESNO:return {type:m.type===M.SELECT_EFFECTYN?R.SELECT_EFFECTYN:R.SELECT_YESNO,yes:true};
 case M.SELECT_PLACE:case M.SELECT_DISFIELD:return {...choices[0].response,places:choices.slice(0,m.count||1).map(c=>c.response.places[0])};
 case M.ANNOUNCE_RACE:return{type:R.ANNOUNCE_RACE,races:Object.values(OcgRace).filter(v=>(v&BigInt(m.available))!==0n).slice(0,m.count)};
 case M.ANNOUNCE_ATTRIB:return{type:R.ANNOUNCE_ATTRIB,attributes:Object.values(OcgAttribute).filter(v=>v&m.available).slice(0,m.count)};
 case M.SELECT_COUNTER:{let remain=m.count;return{type:R.SELECT_COUNTER,counters:m.cards.map(c=>{let n=Math.min(remain,c.count);remain-=n;return n})}}}
 if(choices.length)return choices[0].response;throw Error('Unsupported engine prompt '+ocgMessageTypeStrings.get(m.type));}
 sumValid(m,indices){if(new Set(indices).size!==indices.length||indices.some(i=>i<0||i>=m.selects.length))return false;const chosen=[...(m.selects_must||[]),...indices.map(i=>m.selects[i])];if(!chosen.length)return false;const options=c=>[c.amount&65535,...(c.amount>>>16?[c.amount>>>16]:[])];if(m.select_max){const low=chosen.map(c=>Math.min(...options(c))),high=chosen.map(c=>Math.max(...options(c)));return high.reduce((a,b)=>a+b,0)>=m.amount&&low.reduce((a,b)=>a+b,0)-Math.min(...low)<m.amount}if(indices.length<m.min||indices.length>m.max)return false;let sums=[0];for(const c of chosen)sums=[...new Set(sums.flatMap(n=>options(c).map(v=>n+v)))].filter(n=>n<=m.amount);return sums.includes(m.amount)}
 sumSelection(m,avoid=()=>false){let result=null,nodes=0;const walk=(i,indices)=>{if(result||++nodes>200000)return;if(this.sumValid(m,indices)){result=indices;return}if(i>=m.selects.length||(!m.select_max&&indices.length>=m.max))return;if(!avoid(m.selects[i]))walk(i+1,[...indices,i]);walk(i+1,indices)};walk(0,[]);if(!result)throw Error('No valid material combination found');return result;}
 destroy(){void saveRecording(this);if(this.h){this.core.destroyDuel(this.h);this.h=null}}
}
