export const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function lastPlayed(value){const date=new Date(Number(value)*1000);return value&&Number.isFinite(+date)?date.toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Not recorded';}
export function packSummary(content,pid){const p=content.packs.find(p=>p.id===pid);if(!p)return '';const ids=new Set([...(p.common||[]),...(p.rare||[])]),cards=content.cards.filter(c=>ids.has(c.id)),counts={};for(const c of cards)if(c.data.type&1)counts[c.race]=(counts[c.race]||0)+1;const types=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name])=>name);const themes=[];if(cards.some(c=>c.data.type&128))themes.push('Ritual Summoning');if(cards.some(c=>c.data.type&64))themes.push('Fusion Summoning');if(cards.filter(c=>/destroy|banish|return.*hand/i.test(c.desc)).length>=6)themes.push('removal and control');if(cards.filter(c=>/gain.*LP|increase.*Life Points/i.test(c.desc)).length>=4)themes.push('LP recovery');return `${types.length?'Main monster types: '+types.join(', ')+'. ':''}Support: ${themes.join(', ')||'mixed monsters, Spells and Traps'}. ${ids.size} different cards. Click to inspect.`;}
export function cursedParts(key,text){if(key==='glass_shard')return ['Coin rewards are doubled.','You start every duel with 2000 LP.'];if(key==='cursed_duelists_wager')return ['Battle damage you inflict is increased by 50%.','Battle damage you take is increased by 50%.'];if(key==='cursed_narrow_gate')return ['Your opponent has only 3 Main Monster Zones and 3 Spell & Trap Zones.','You also have only 3 of each. Field Zones are unaffected.'];let at=text.indexOf(', but ');if(at>=0)return [text.slice(0,at)+'.',text.slice(at+6)];at=text.search(/\.\s+(?=[A-Z])/);if(at>=0)return [text.slice(0,at+1),text.slice(at+2)];return [text,'This effect also changes your own side of the duel.'];}
export function cursedMarkup(key,text){const [good,bad]=cursedParts(key,text);return `<div class="relic-benefit" aria-label="Benefit"><p>${safe(good)}</p></div><div class="relic-drawback" aria-label="Drawback"><p>${safe(bad)}</p></div>`;}
export const EFFECT_FILTERS={'Any effect':null,'Removal':/destroy|banish|return.*(?:hand|deck)/i,'Draw / search':/draw|add.*(?:deck|gy|graveyard).*hand/i,'Recovery':/gain.*LP|increase.*Life Points|recover/i,'Negation':/negate/i,'Summoning':/Special Summon|Ritual Summon|Fusion Summon/i,'ATK / DEF':/ATK|DEF/i};
export function matchesFilters(c,type,attribute,effect){return (!type||type==='All types'||(type==='Monster'?c.data.type&1:type==='Spell'?c.data.type&2:c.data.type&4))&&(!attribute||attribute==='All attributes'||c.attribute===attribute)&&(!EFFECT_FILTERS[effect]||EFFECT_FILTERS[effect].test(c.desc||''));}
export function materialStatus(m,selected,engine,M){const indices=[...selected];if(m.type===M.SELECT_UNSELECT_CARD)return {valid:!!m.can_finish,text:m.can_finish?'Selection is valid.':'Choose or remove materials to complete the selection.'};if(m.type===M.SELECT_SUM){const chosen=[...(m.selects_must||[]),...indices.map(i=>m.selects[i])];const low=chosen.reduce((n,c)=>n+Math.min(c.amount&65535,(c.amount>>>16)||(c.amount&65535)),0),high=chosen.reduce((n,c)=>n+Math.max(c.amount&65535,c.amount>>>16),0);const valid=engine.sumValid(m,indices);return {valid,text:`Selected Levels: ${low===high?low:low+'–'+high} / ${m.amount}${m.select_max?' or more':''}. ${valid?'Valid materials.':'Choose a valid combination; extra unnecessary materials cannot be used.'}`};}const units=indices.reduce((n,i)=>n+(m.type===M.SELECT_TRIBUTE?(m.selects[i].release_param||1):1),0);const valid=units>=m.min&&indices.length<=m.max;return {valid,text:valid?'Selection is valid.':`Selected ${units}; choose ${m.min}–${m.max}${m.type===M.SELECT_TRIBUTE?' tribute value':' cards'}.`};}

// Compact boss-curse buttons share the same descriptions in solo and tag.
export function curseDescription(content,key,level=0){return level>=2?({frailty:'Your monsters lose 400 ATK.',enemy_power:'Enemy monsters gain 400 ATK.',hunger:'Your monsters lose 600 DEF.',tax:'Take 1000 damage at the end of each of your turns.',mercy:'Your outgoing battle damage is reduced to one quarter.',drain:'Start this boss duel with 1000 fewer LP, minimum 1.'}[key]||content.curses[key]?.[1]||''):content.curses[key]?.[1]||'';}
export function curseIcons(content,keys,tag=false){return `<div class="opponent-curses" aria-label="Boss curses">${keys.map(key=>{const icon={frailty:'increase-decrease-atk-def',hunger:'increase-decrease-atk-def',enemy_power:'increase-decrease-atk-def',tax:'reduce-life-points',drain:'reduce-life-points',mercy:'restrict-attack',relic_seal:'cancel-out-effect'}[key]||'cancel-out-effect';const name=content.curses[key]?.[0]||key;return `<button class="curse-icon curse-${safe(key)}" ${tag?'data-tag':'data-do'}="curse-info" data-curse="${safe(key)}" aria-label="${safe(name)}" title="${safe(name)}"><img src="assets/icons/yugipedia/genres-${icon}.png" alt=""></button>`}).join('')}</div>`;}

export function victoryRewardsMarkup(rewards,bonusLabels){
 const labels=new Set(bonusLabels||[]),earned=Object.entries(rewards||{}).filter(([,value])=>value),bonuses=earned.filter(([label])=>labels.has(label));
 const row=([label,value])=>`<p class="row"><span>${safe(label)}</span><b>${value>0?'+':''}${value}</b></p>`;
 const ordinary=earned.filter(([label])=>!labels.has(label)).map(row).join('');
 return ordinary+(bonuses.length?`<details class="battle-bonuses"><summary><span>Battle bonuses</span><b>+${bonuses.reduce((sum,[,value])=>sum+value,0)}</b></summary><div class="battle-bonus-list" tabindex="0" role="region" aria-label="Earned battle bonuses">${bonuses.map(row).join('')}</div></details>`:'');
}

export function shopRerollPrice(run){const n=Math.max(0,Math.trunc(run.shop_rerolls||0));return n<6?[10,20,40,60,100,150][n]:200+50*(n-6)}
