import {forcedUltra as ULTRA_RARE} from './ultra-rarity.js';
let active=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Presentation only: every card is already awarded and saved before this opens.
export function openPacks({packs,content,image,inspect,sound=()=>{},stopSound=()=>{},done=()=>{}}){
 active?.();if(!packs.length){done();return}
 packs=packs.map(p=>({...p,cards:[...(p.cards||[])].sort((a,b)=>Number(ULTRA_RARE.has(a))-Number(ULTRA_RARE.has(b)))}));
 const dialog=document.createElement('dialog');dialog.className='pack-theatre';document.body.append(dialog);
 let index=0,revealed=0,timers=[],closed=false,opening=false,jackpot=false;
 const later=(fn,ms)=>timers.push(setTimeout(()=>{if(!closed)fn()},ms*1.2));
 const clear=()=>{timers.forEach(clearTimeout);timers=[]};
 const finish=()=>{if(closed)return;closed=true;clear();stopSound();dialog.close();dialog.remove();if(active===finish)active=null;done()};active=finish;
 function burst(rare=false){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const fx=document.createElement('div');fx.className='pack-burst'+(rare?' gold':'');fx.setAttribute('aria-hidden','true');for(let i=0;i<(rare?28:42);i++){const dot=document.createElement('i'),angle=i*2.39996,distance=70+(i%7)*22;dot.style.setProperty('--dx',Math.cos(angle)*distance+'px');dot.style.setProperty('--dy',Math.sin(angle)*distance+'px');dot.style.setProperty('--delay',(i%5)*.025+'s');fx.append(dot)}dialog.append(fx);later(()=>fx.remove(),1400)}
 const info=()=>content.packs.find(p=>p.id===packs[index].id);
 const ids=()=>packs[index].cards||[];
 function cardMarkup(id,n){const c=content.cards.find(c=>c.id===id),rare=info()?.rare_display?.includes(id),ultra=ULTRA_RARE.has(id);return `<button class="pack-pull ${rare?'rare':''} ${ultra?'ultra':''}" data-reveal="${n}" aria-label="Reveal card ${n+1}"><img src="assets/card-back.jpg" alt="Face-down card"><span>?</span></button>`}
 function revealOne(){if(revealed>=ids().length)return;const n=revealed++,id=ids()[n],el=dialog.querySelector(`[data-reveal="${n}"]`),c=content.cards.find(c=>c.id===id);el.classList.add('turned');el.dataset.inspect=id;el.setAttribute('aria-label','Inspect '+(c?.name||'card'));el.innerHTML=`<img src="${image(id)}" alt="${esc(c?.name)}"><span>${esc(c?.name)}</span>${el.classList.contains('ultra')?'<b>ULTRA RARE</b>':el.classList.contains('rare')?'<b>RARE</b>':''}`;if(el.classList.contains('ultra')){el.insertAdjacentHTML('beforeend','<i class="card-sparkles" aria-hidden="true">✦<em>✧</em><strong>✦</strong></i>');burst(true);if(!jackpot){jackpot=true;sound('pack-rare');const rain=document.createElement('img');rain.className='pack-money';rain.src='assets/effects/money-rain.gif';rain.alt='';rain.setAttribute('aria-hidden','true');dialog.append(rain);later(()=>rain.remove(),9000)}}else sound(el.classList.contains('rare')?'rare-shimmer':'card-reveal');dialog.querySelector('.pack-progress').textContent=`${revealed} / ${ids().length} revealed`;if(revealed===ids().length){dialog.querySelector('.pack-next').hidden=false;dialog.querySelector('.pack-skip').hidden=true;dialog.classList.add('all-revealed')}}
 function revealAll(){if(!opening)open(true);clear();dialog.querySelectorAll('.pack-burst,.pack-money').forEach(e=>e.remove());while(revealed<ids().length){revealOne()} }
 function open(instant=false){if(opening)return;opening=true;dialog.classList.add('opening');burst();sound('pack-rustle');dialog.querySelector('.pack-open').disabled=true;
  const deal=()=>{dialog.querySelector('.pack-stage').innerHTML=`<div class="pack-reveal-dust" aria-hidden="true">${Array.from({length:22},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="pack-pulls">${ids().map(cardMarkup).join('')}</div>`;dialog.querySelector('.pack-skip').hidden=false;if(!instant)ids().forEach((_,i)=>later(revealOne,200+i*210));};if(instant)deal();else later(deal,650);
 }
 function show(){clear();stopSound();opening=false;revealed=0;jackpot=false;dialog.classList.remove('opening','all-revealed');const p=info();dialog.innerHTML=`<header><div><small>BOOSTER ${index+1} / ${packs.length}</small><h2>${esc(p?.name||'Your cards')}</h2></div><button class="pack-close">Close</button></header><div class="pack-stage"><div class="pack-aura" aria-hidden="true"></div><div class="pack-sparks" aria-hidden="true">${Array.from({length:16},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><button class="pack-open" aria-label="Open pack"><img src="${p?'assets/packs/'+p.id+'.jpg':'assets/card-back.jpg'}" alt="${esc(p?.name||'Cards')}"><strong>OPEN PACK</strong></button></div><footer><span class="pack-progress">Your cards are already in your collection</span><button class="pack-skip" hidden>Reveal all</button><button class="pack-next primary" hidden>${index+1<packs.length?'Next pack':'Continue'}</button></footer>`}
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;e.stopPropagation();if(b.dataset.inspect){inspect(Number(b.dataset.inspect));return}if(b.classList.contains('pack-close'))finish();else if(b.classList.contains('pack-open'))open();else if(b.classList.contains('pack-skip'))revealAll();else if(b.classList.contains('pack-next')){index++;index<packs.length?show():finish()}});
 dialog.addEventListener('cancel',e=>{e.preventDefault();finish()});show();dialog.showModal();return finish;
}
