const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),content=JSON.parse(fs.readFileSync(path.join(root,'android/web/content.json')));
const sources=JSON.parse(fs.readFileSync(path.join(root,'data/wc4-pack-sources.json'))).packs;
const aliases={'Red-Eyes B. Dragon':'Red-Eyes Black Dragon','B. Skull Dragon':'Black Skull Dragon'};
const colors=['#71b6ee','#bb6478','#9766b1','#829da9','#698cae','#9685cb','#bc91d4','#8db78d','#8496bf','#b8878a','#7987a5','#8f789e','#bc806e','#c3a56a','#b482ae','#80a4ce','#b28bd7','#71afb0','#cca875','#60c494','#e56a9b','#e3c66b','#ab75dd','#dfb965'];
const packs=sources.map((p,i)=>{const c=content.cards.find(c=>c.name===(aliases[p.name]||p.name));if(i<14&&!c)throw Error('Missing card '+p.name);return {...p,card:c?.id,portrait:i>=14&&i<19?'pack-components/yugi-official-'+(i-13)+'.jpg':null,tint:colors[i],kind:i<14?'card':i<19?'yugi':i<23?'puzzle':'eye',variant:i>=14&&i<19?i-13:null}});
const css=`*{box-sizing:border-box}html,body{margin:0;background:#fff}#pack{width:360px;height:720px;position:relative;overflow:hidden;border:1px solid #666;background:var(--tint)}.official-scene{position:absolute;left:0;bottom:22px;width:100%;height:380px;object-fit:cover;object-position:65% center}.original-symbol{position:absolute;inset:22px 0;overflow:hidden}.original-symbol svg{width:100%;height:100%}.art{position:absolute;inset:22px 0;overflow:hidden}.art svg{width:100%;height:100%}.wash{position:absolute;inset:22px 0;background:linear-gradient(color-mix(in srgb,var(--tint) 40%,#fff) 0%,color-mix(in srgb,var(--tint) 60%,transparent) 32%,transparent 65%,#08112044)}.logo{z-index:2;position:absolute;top:38px;left:47px;width:266px;filter:drop-shadow(0 1px 1px #fff8)}.subject{z-index:1;position:absolute;left:0;bottom:53px;width:100%;height:360px;object-fit:contain;filter:drop-shadow(0 5px 5px #10192c88)}.puzzle .subject{padding:18px;filter:sepia(1) saturate(3) hue-rotate(var(--hue)) drop-shadow(0 0 14px #fff8)}.eye .subject{padding:12px}.yugi .subject{height:398px}.symbol-glow{position:absolute;inset:22px 0;background:radial-gradient(ellipse at 50% 67%,#ffffffb0,transparent 50%),repeating-conic-gradient(from 15deg at 50% 64%,#ffffff22 0deg 2deg,transparent 2deg 28deg)}.name{z-index:3;position:absolute;bottom:22px;left:0;right:0;padding:9px 8px;text-align:center;font:bold 15px Georgia;color:#fff3ce;background:linear-gradient(transparent,#0a1024ba);text-shadow:0 1px 3px #000;letter-spacing:.5px}.seal{z-index:3;position:absolute;left:0;right:0;height:22px;background:linear-gradient(#333 0%,#a5a5a5 16%,#f9f9f9 32%,#858585 48%,#dedede 65%,#fff 78%,#888 100%)}.top{top:0}.bottom{bottom:0;transform:rotate(180deg)}`;
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<style>'+css+'</style><div id="pack"></div>');return}const f=path.resolve(root,'.'+decodeURIComponent(req.url));if(!f.startsWith(root+path.sep)){res.writeHead(403);res.end();return}try{res.end(fs.readFileSync(f))}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:360,height:720},deviceScaleFactor:2});await page.goto(`http://127.0.0.1:${server.address().port}/`);
for(const p of packs){await page.evaluate(async p=>{const pack=document.querySelector('#pack');pack.className=p.kind;pack.style.setProperty('--tint',p.tint);pack.style.setProperty('--hue',({'WC4-20':75,'WC4-21':285,'WC4-22':0,'WC4-23':220}[p.id]||0)+'deg');let art='';if(p.card){const im=new Image();im.src='/assets/cards/'+p.card+'.jpg';await im.decode();const w=im.naturalWidth,h=im.naturalHeight;art=`<div class="art"><svg viewBox="0 0 ${w*.76} ${h*.508}" preserveAspectRatio="xMidYMid slice"><image href="${im.src}" x="${-w*.12}" y="${-h*.192}" width="${w}" height="${h}"/></svg></div>`;}else if(p.kind==='yugi'){art=`<img class="official-scene" style="object-position:${p.variant===4?100:65}% center" src="/assets/${p.portrait}">`;}else{art=`<div class="original-symbol"><svg viewBox="0 8 48 60" preserveAspectRatio="none"><image href="/assets/pack-components/original-${p.id}.jpg" width="48" height="103"/></svg></div>`;}pack.innerHTML=art+'<div class="wash"></div><img class="logo" src="/assets/pack-components/wct2004-logo.png"><div class="seal top"></div><div class="seal bottom"></div>';await Promise.all([...document.images].map(i=>i.decode()));},p);await page.locator('#pack').screenshot({path:path.join(root,'assets/packs',p.id+'.jpg'),type:'jpeg',quality:94});}
fs.writeFileSync(path.join(root,'data/wc4-pack-art.json'),JSON.stringify({layout:'Silver foil wrapper, supplied WCT 2004 logo, original card subjects and themed colors',packs:packs.map(({id,name,card,portrait,tint,kind,variant})=>({id,name,card,portrait,tint,kind,variant})),artSources:JSON.parse(fs.readFileSync(path.join(root,'assets/pack-components/official-sources.json'))),symbolSources:'Original official WC2004 game pack illustrations; no generated replacements'},null,2)+'\n');
await page.setViewportSize({width:1440,height:1080});await page.setContent('<style>body{margin:0;padding:18px;background:#10232d;display:grid;grid-template-columns:repeat(8,1fr);gap:12px;align-content:start}img{width:100%;display:block}</style>'+packs.map(p=>`<img src="http://127.0.0.1:${server.address().port}/assets/packs/${p.id}.jpg">`).join(''));await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:path.join(root,'temp/wc4-pack-covers.jpg'),fullPage:true,type:'jpeg',quality:90});await page.setViewportSize({width:1250,height:500});await page.setContent('<style>body{margin:0;padding:12px;background:#10232d;display:flex;gap:12px}img{width:235px;height:470px}</style>'+packs.filter(p=>p.kind==='yugi').map(p=>`<img src="http://127.0.0.1:${server.address().port}/assets/packs/${p.id}.jpg">`).join(''));await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:path.join(root,'temp/yugi-pack-covers.jpg'),type:'jpeg',quality:92});console.log('Rendered and indexed all '+packs.length+' GBA pack covers.');}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});


