const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const content=JSON.parse(fs.readFileSync(path.join(root,'android/web/content.json'),'utf8'));
const themes={
'Yami Yugi':'#ac79d8','Seto Kaiba':'#71b6ee','Joey Wheeler':'#e8a34e','Mai Valentine':'#bf8be0','Bandit Keith':'#839fac','Lumis and Umbra':'#8696c8','Yami Bakura':'#a286c5','Maximillion Pegasus':'#dc91b6','Rex Raptor':'#9fb96b','Bonz':'#9db581','Weevil Underwood':'#95c775','Yami Marik':'#d694b7','Tristan Taylor':'#c49a73','Yugi Muto':'#ceae66','Ishizu Ishtar':'#74c2bc','Odion':'#d2a65f','Espa Roba':'#7cbfb8','Arkana':'#d18399','Mako Tsunami':'#67bada','Duke Devlin':'#7fa894','Noah Kaiba':'#8fcab5','Paradox Brothers':'#83b39d','Tea Gardner':'#e4a3b9','Solomon Muto':'#c8b378','Mokuba Kaiba':'#85a9d4','Rebecca Hawkins':'#ba9fda','Serenity Wheeler':'#e7bb94','Marik Ishtar':'#c5a4da','Anubis':'#d4b877','Shadi':'#77bfb9','PaniK':'#9985b9','Rafael':'#a2b58a'};
const packs=content.packs.filter(p=>p.draft_only).map(p=>{const c=content.characters.find(c=>c.starting_packs?.includes(p.id));if(!c)throw Error('No character for '+p.id);const card=content.cards.find(x=>x.name===c.cards[0]);if(!card)throw Error('No signature for '+c.name);return {id:p.id,name:c.name,sprite:c.sprite,card:card.id,signature:card.name,tint:themes[c.name]||'#9ab5ca'}});
const css=`*{box-sizing:border-box}html,body{margin:0;background:#fff}#pack{width:360px;height:720px;position:relative;overflow:hidden;background:color-mix(in srgb,var(--tint) 45%,white);border:1px solid #666}.signature{position:absolute;inset:22px 0;overflow:hidden;filter:saturate(.72) contrast(.68) brightness(1.18);opacity:.74}.signature svg{width:100%;height:100%}.wash{position:absolute;inset:22px 0;background:linear-gradient(color-mix(in srgb,var(--tint) 45%,transparent),color-mix(in srgb,var(--tint) 30%,transparent) 40%,color-mix(in srgb,var(--tint) 45%,transparent))}.logo{position:absolute;top:55px;left:14px;width:330px;height:auto;filter:drop-shadow(0 1px 0 white)}.portrait{position:absolute;left:0;bottom:22px;width:100%;height:375px;object-fit:contain;object-position:center bottom;filter:drop-shadow(0 2px 2px #0002)}.seal{position:absolute;left:0;right:0;height:22px;background:linear-gradient(#333 0%,#a5a5a5 16%,#f9f9f9 32%,#858585 48%,#dedede 65%,#fff 78%,#888 100%);box-shadow:0 1px 2px #0005}.top{top:0}.bottom{bottom:0;transform:rotate(180deg)}`;
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<style>'+css+'</style><div id="pack"></div>');return}const f=path.resolve(root,'.'+decodeURIComponent(req.url));if(!f.startsWith(root+path.sep)){res.writeHead(403);res.end();return}try{res.end(fs.readFileSync(f))}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:360,height:720},deviceScaleFactor:2});await page.goto(`http://127.0.0.1:${server.address().port}/`);
for(const p of packs){await page.evaluate(async p=>{const im=new Image();im.src='/assets/cards/'+p.card+'.jpg';await im.decode();const w=im.naturalWidth,h=im.naturalHeight;document.querySelector('#pack').style.setProperty('--tint',p.tint);document.querySelector('#pack').innerHTML=`<div class="signature"><svg viewBox="0 0 ${w*.76} ${h*.508}" preserveAspectRatio="xMidYMid slice"><image href="${im.src}" x="${-w*.12}" y="${-h*.192}" width="${w}" height="${h}"/></svg></div><div class="wash"></div><img class="logo" src="/assets/rogue-duelist-logo.png"><img class="portrait" src="/assets/${p.sprite}"><div class="seal top"></div><div class="seal bottom"></div>`;await Promise.all([...document.images].map(i=>i.decode()));},p);await page.locator('#pack').screenshot({path:path.join(root,'assets/packs',p.id+'.jpg'),type:'jpeg',quality:95});}
fs.writeFileSync(path.join(root,'data/character-pack-art.json'),JSON.stringify({layout:'Silver sealed themed-color pack, moderately contrasted signature-card art background, logo, bottom-anchored character portrait',packs},null,2)+'\n');console.log('Rendered '+packs.length+' custom pack covers using their first signature cards.');
}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
