import assert from 'node:assert/strict';
import {chainWindowAllowed,automaticChainResponse} from '../android/web/duel-presentation.js';
import {OcgHintTiming as T} from '../android/web/vendor/package/dist/index.js';
import {FieldKnowledge} from '../android/web/field-knowledge.js';
import {MobileDuel,M,R,L} from '../android/web/duel.js';
import {smartContext} from '../android/web/smart_policy.js';
import fs from 'node:fs';
for(const timing of [T.SUMMON,T.SPSUMMON,T.FLIPSUMMON,T.ATTACK])assert(chainWindowAllowed({hint_timing:timing},'sometimes'));
for(const timing of [0,T.DRAW_PHASE,T.STANDBY_PHASE,T.END_PHASE,T.CHAIN_END,T.DAMAGE_STEP])assert(!chainWindowAllowed({hint_timing:timing},'sometimes'));
assert(chainWindowAllowed({},'sometimes',[{code:1}]));assert(chainWindowAllowed({forced:true},'never'));assert(!chainWindowAllowed({},'never',[{}]));
assert.deepEqual(automaticChainResponse({player:0,type:M.SELECT_CHAIN,forced:true,selects:[{}]},true,M,R),{type:R.SELECT_CHAIN,index:0});
const k=new FieldKnowledge(),c={controller:1,location:L.MZONE,sequence:0,position:8,code:123};
assert.equal(k.known(0,c),0);k.message({type:M.CONFIRM_CARDS,player:0,cards:[c]},M,L);assert.equal(k.known(0,c),123);assert.equal(k.known(1,c),0);
k.message({type:M.NEW_TURN},M,L);assert.equal(k.known(0,c),123);k.message({type:M.SHUFFLE_SET_CARD,cards:[{from:c,to:c}]},M,L);assert.equal(k.known(0,c),0);
const content=JSON.parse(fs.readFileSync(new URL('../android/web/content.json',import.meta.url)));const cards=content.cards,byName=n=>cards.find(c=>c.name===n),panther=byName('Panther Warrior'),jinzo=byName('Jinzo');
const a={code:panther.id,controller:1,location:L.MZONE,sequence:0,position:1,attack:2000},b={code:jinzo.id,controller:1,location:L.MZONE,sequence:1,position:1,attack:4000};
const e={cards:new Map(cards.map(c=>[c.id,c])),data:Object.fromEntries(cards.map(c=>[c.id,c.data])),name:id=>cards.find(c=>c.id===id)?.name,query:(p,l)=>p===1&&l===L.MZONE?[a,b]:[],turn:8,phase:8,player:1,lp:[3000,4000],activeChain:[],aiModifiers:{}};
let s=smartContext(e,1,L,{});assert(!s.pantherTributeAllowed(a,b,true));assert(!s.attackAllowed(a,true));e.lp[0]=2000;s=smartContext(e,1,L,{});assert(s.pantherTributeAllowed(a,b,true));assert(!s.pantherTributeAllowed(a,b,false));
b.attack=1000;e.lp[0]=8000;s=smartContext(e,1,L,{});assert(s.pantherTributeAllowed(a,b,false));
console.log('PASS chain modes/mandatory effects, private reveal memory/invalidation, Panther stronger-tribute/lethal/weak-fodder rules');
import {dnaSurgeryRace} from '../android/web/dna-surgery-policy.js';
import {OcgRace as Race} from '../android/web/vendor/package/dist/index.js';
const normal=n=>byName(n).id,dragon=normal('Blue-Eyes White Dragon'),insect=normal('Man-Eater Bug'),warrior=normal('Axe Raider'),barrier=normal('Insect Barrier'),forces=normal('The A. Forces');
let zones=[[],[]];e.replayRecord={start:[[],[dragon,dragon,dragon,insect,warrior]]};e.query=(p,l)=>l===L.SZONE?zones[p]:l===L.MZONE?(p===1?[a,b]:[]):[];
const available=(1n<<26n)-1n;assert.equal(dnaSurgeryRace(e,1,L,available),Race.DRAGON);
zones[1]=[{code:barrier,position:1,sequence:0}];assert.equal(dnaSurgeryRace(e,1,L,available),Race.INSECT);
zones[1][0].is_disabled=true;assert.equal(dnaSurgeryRace(e,1,L,available),Race.DRAGON);
zones[1]=[{code:forces,position:1,sequence:0}];assert.equal(dnaSurgeryRace(e,1,L,available),Race.WARRIOR);
zones[1]=[];zones[0]=[{code:barrier,position:1,sequence:0}];e.replayRecord.start[1]=[insect,insect,insect,warrior];assert.equal(dnaSurgeryRace(e,1,L,available),Race.WARRIOR);
assert.equal(dnaSurgeryRace(e,1,L,Race.DRAGON),Race.DRAGON);
console.log('PASS DNA deck majority, own/opposing continuous effects, disabled effects, legal race mask');
zones[0]=[];zones[1]=[{code:normal('Forgotten Temple of the Deep'),position:1,sequence:0}];const sea=cards.find(c=>c.race==='Sea Serpent'&&c.data?.type&1);assert(sea);e.replayRecord.start[1]=[dragon,dragon,dragon,sea.id];assert.equal(dnaSurgeryRace(e,1,L,available),Race.SEASERPENT);
console.log('PASS Sea Serpent continuous-effect support');
