const {chromium}=require('C:/Users/Win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/test'){res.setHeader('Content-Type','text/html');res.end('<div id=field></div>');return}const f=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(root+path.sep)){res.writeHead(403);res.end();return}try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.json')?'application/json':f.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(f))}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,channel:'chrome',args:['--js-flags=--expose-gc','--enable-precise-memory-info']});const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto('http://127.0.0.1:'+server.address().port+'/test');await page.route('**/campaign-files.json',r=>r.abort());
await page.setContent('<div id="field"></div>');
const result=await page.evaluate(async()=>{
const base=location.origin+'/android/web/';const {waitForTossStart}=await import(base+'duel-presentation.js');let finished=false;const wait=waitForTossStart(document.querySelector('#field'),'coin',()=>true).then(x=>finished=x);await new Promise(r=>setTimeout(r,100));if(finished)throw Error('Started without tap');document.querySelector('.toss-start').click();await wait;if(!finished||document.querySelector('.toss-start'))throw Error('Tap failed cleanup');
const canceled=waitForTossStart(document.querySelector('#field'),'dice',()=>true);document.querySelector('#field').replaceChildren();if(await canceled)throw Error('Detached gate was not canceled');
const {MobileDuel}=await import(base+'duel.js');const read=async n=>(await fetch(base+n+'.json')).json();const content=await read('content'),fixtures=await (await fetch('/tools/fixtures/wct2004-regressions.json')).json(),row=fixtures[0];const e=await new MobileDuel(content.cards).init([await read('engine-data'),await read('scripts')]);
const runs=[];for(let i=0;i<40;i++){const t=performance.now();e.start(row.main,row.enemyMain,8000,8000,5,row.seed,row.extra,row.enemyExtra);let steps=0;while(!e.finished&&steps++<5000&&e.turn<160)e.respond(e.auto());if(!e.finished||e.errors.length)throw Error('Duel failed '+i);e.destroy();globalThis.gc();runs.push({duel:i+1,steps,ms:Math.round(performance.now()-t),heap:performance.memory.usedJSHeapSize});await new Promise(r=>setTimeout(r,10));}return runs;
});console.log(JSON.stringify(result));fs.writeFileSync(path.join(root,'temp/memory-soak-results.json'),JSON.stringify(result,null,2));assert.equal(result.length,40);const baseline=Math.max(...result.slice(5,10).map(r=>r.heap)),tail=Math.max(...result.slice(-5).map(r=>r.heap));assert.ok(tail-baseline<4*1024*1024,'Retained heap grew by '+(tail-baseline));console.log('PASS 40 duels: post-GC heap growth after warmup '+(tail-baseline)+' bytes');}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});

