const {chromium}=require('C:/Users/Win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome',args:['--mute-audio','--disable-features=LocalNetworkAccessChecks']});const errors=[];
try{const contexts=await Promise.all([browser.newContext({viewport:{width:390,height:844}}),browser.newContext({viewport:{width:932,height:430}})]);const pages=[];
for(let seat=0;seat<2;seat++){const page=await contexts[seat].newPage();pages.push(page);page.on('console',m=>{if(m.type()==='error')console.log(m.text())});page.on('response',async r=>{if(r.status()>=400)console.log('HTTP',r.url(),await r.text())});page.on('requestfailed',r=>console.log('FAILED',r.url(),r.failure()));page.on('pageerror',e=>errors.push(e.message));await page.route('**/index.html',r=>r.fulfill({contentType:'text/html',body:'<html><head><link rel="stylesheet" href="mobile.css"></head><body><main id="app"></main><dialog id="modal"></dialog></body></html>'}));await page.route('**/multiplayer-config.json',r=>r.fulfill({json:{signalingUrl:'http://127.0.0.1:8791'}}));await page.goto('http://127.0.0.1:4392/index.html');await page.evaluate(async seat=>{
 const {CollectorUI}=await import('./collector-ui.js');const content=await fetch('content.json').then(r=>r.json());const ids=content.cards.filter(c=>c.type==='Normal Monster'&&c.atk>=1500&&c.atk<=2000&&c.level<=4).slice(0,20).map(c=>c.id);const pool=ids.flatMap(id=>[id,id]);const id=crypto.randomUUID(),d={id,token:crypto.randomUUID()+crypto.randomUUID(),name:'Collector QA '+seat,character:seat,slot:1,status:'alive',pool,deck:{main:pool,side:[],extra:[]},history:[],wins:0};let data={duelists:[d]};const root=document.getElementById('app');window.ui=new CollectorUI({root,content,image:id=>'assets/cards/'+id+'.jpg',getSlots:()=>[],inspect:()=>{},dialog:(t,b)=>{window.lastDialog=t+': '+b;console.error(window.lastDialog)},onExit:()=>{},onView:()=>{},onDuel:()=>{},backend:async(action,value)=>{if(action==='collector-list')return data;if(action==='collector-sync'){Object.assign(d,value.record);return data;}throw Error(action);}});await ui.init();ui.duelist=d;await ui.sync(await ui.api('deck',{deck:{main:pool,side:[],extra:[]}}));ui.mode='home';ui.render();
},seat);await page.screenshot({path:'temp/collector-home-'+seat+'.png'});}
await pages[0].evaluate(()=>ui.action('host'));const code=await pages[0].evaluate(()=>ui.room.code);await pages[1].evaluate(async code=>{await ui.accept(await ui.api('join',{code}));ui.schedule()},code);await pages[0].waitForFunction(()=>ui.game,{timeout:30000});
for(let steps=0;steps<500;steps++){
 await Promise.all(pages.map(p=>p.evaluate(()=>ui.enqueue(async()=>{clearTimeout(ui.timer);await ui.accept(await ui.api('poll'));}))));
 const state=await pages[0].evaluate(()=>({phase:ui.room.phase,seat:ui.game?.respondingSeat^ui.room.first,n:ui.applied,finished:!!ui.game?.finished}));if(state.phase==='complete'){console.log('Match completed after',steps,'actions');break;}if(state.phase==='siding'){for(const p of pages)await p.evaluate(()=>ui.enqueue(async()=>{await ui.accept(await ui.api('side',{deck:ui.room.decks[ui.seat]}));if(ui.seat===ui.room.chooser)await ui.accept(await ui.api('first',{first:ui.seat}));}));continue;}if(state.finished)continue;
 const page=pages[state.seat];await page.evaluate(async()=>{await ui.enqueue(async()=>ui.request('duel-response',{number:ui.applied,response:(ui.seat^ui.room.first)?(await import('./tag-duel.js')).flipPerspective(ui.game.auto()):ui.game.auto()}))});
 if(steps===10){await pages[0].evaluate(()=>ui.enqueue(async()=>{ui.game.destroy();ui.game=null;await ui.accept(await ui.api('poll'));}));console.log('Reconstructed engine from saved actions');}
 if(steps===499)throw Error('Duel did not complete');
}
const winner=await pages[0].evaluate(()=>ui.room.winner);await pages[winner].screenshot({path:'temp/collector-victory.png'});await pages[1-winner].screenshot({path:'temp/collector-shadow-realm.png'});await pages[winner].evaluate(()=>ui.enqueue(async()=>{await ui.accept(await ui.api('prizes',{indices:[0,1,2,3,4]}));}));assert.equal(await pages[winner].evaluate(()=>ui.duelist.pool.length),45);assert.equal(await pages[1-winner].evaluate(()=>ui.duelist.status),'eliminated');assert.deepEqual(errors,[]);console.log('Collector two-client MR2 duel and replay recovery passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
